-- Seed catalog: 368 SKUs. Idempotent via on conflict do update.
-- Regenerate with: node /tmp/gen_seed.js > supabase/seed/products.sql

insert into public.products (id, name, brand, cat, sub, sku, flavors, variants, img, tag, price, active) values
  (1, 'SS', 'SS', 'TOBACCO', 'Cigars & Cigarillos', 'AW-SS', 15, '["diamond","red","green","white grape","silver","grape","mango blaze","cookies & cream"]'::jsonb, 'ss_cigarillos.avif', null, 41.76, true),
  (2, 'WO', 'WO', 'TOBACCO', 'Cigars & Cigarillos', 'AW-WO', 12, '["Silver","platinum","red sweet","green sweet","black sweet","emerald","white grape","swirl Triple grape"]'::jsonb, 'wo_cigarillos.jpg', null, 84.34, true),
  (3, 'Game', 'Game', 'TOBACCO', 'Cigars & Cigarillos', 'AW-GAME', 11, '["diamond","silver","red sweet","green","black sweet","honey","white grape","grape"]'::jsonb, 'game_cigarillos.webp', null, 62.97, true),
  (4, 'BLK', 'BLK', 'TOBACCO', 'Cigars & Cigarillos', 'AW-BLK', 7, '["smooth","wine","berry","grape","cherry","cocoa","cream"]'::jsonb, 'blk_cigarillos.avif', null, 80, true),
  (5, '4K Cigars', '4K Cigars', 'TOBACCO', 'Cigars & Cigarillos', 'AW-4K-CIGARS', 9, '["Red sweet","watermelon","Napa grape","white grape","diamond","green","black sweet","watermelon grape"]'::jsonb, '4k_cigarillos.webp', null, 51.51, true),
  (6, 'Game Mini', 'Game', 'TOBACCO', 'Cigars & Cigarillos', 'AW-GAME-MINI', 3, '["diamond","red sweet","black sweet"]'::jsonb, 'game_mini.webp', null, 85.05, true),
  (7, 'SS mini', 'SS mini', 'TOBACCO', 'Cigars & Cigarillos', 'AW-SS-MINI', 4, '["diamond","red","grape","green"]'::jsonb, null, null, 45.1, true),
  (8, 'SS leaf', 'SS leaf', 'TOBACCO', 'Wraps & Leafs', 'AW-SS-LEAF', 8, '["Irish cream","honey","sweet aromatic","red","green","peach","dark leaf","dark aromatic"]'::jsonb, 'ss_leaf.jpg', null, 27.02, true),
  (9, 'Ez roll', 'Ez roll', 'TOBACCO', 'Cigars & Cigarillos', 'AW-EZ-ROLL', 10, '["flavorless","OGK","sour apple","wet mango","purple haze","strawberry","blueberry","Jamaican rum"]'::jsonb, null, null, 103.53, true),
  (10, '4K wrap', '4K wrap', 'TOBACCO', 'Wraps & Leafs', 'AW-4K-WRAP', 8, '["diamond","white grape","red sweet","green sweet","black sweet","Napa grape","blueberry","watermelon"]'::jsonb, '4k_wraps.jpg', null, 84.59, true),
  (11, 'Backwoods 5pk', 'Backwoods', 'TOBACCO', 'Cigars & Cigarillos', 'AW-BACKWOODS-5PK', 8, '["banana","honey berry","sweet aromatic","original","Russian cream","vanilla","Black Russian","Irish cream"]'::jsonb, 'backwoods_5pk.webp', 'BESTSELLER', 45.4, true),
  (12, 'Loose leafs 2pk $2.99 OR $1.99', 'Loose', 'TOBACCO', 'Wraps & Leafs', 'AW-LOOSE-LEAFS-2P', 6, '["cinnamon milk","sweet","honey","cookies cream","natural","amber dream"]'::jsonb, 'loose_leafs_2_99_1_99.webp', null, 61.46, true),
  (13, 'Havana leaf', 'Havana', 'TOBACCO', 'Wraps & Leafs', 'AW-HAVANA-LEAF', 9, '["milk cookies","sweet aromatic","strawberry","8 Miles","Russian cream","Purple","yellow","honey bourbon"]'::jsonb, null, null, 62.02, true),
  (14, 'Kite', 'Kite', 'TOBACCO', 'Cigarettes', 'AW-KITE', 0, '[]'::jsonb, 'kite.png', null, 43.33, true),
  (15, 'Royal bunts mini', 'Royal', 'TOBACCO', 'Cigars & Cigarillos', 'AW-ROYAL-BUNTS-MI', 3, '["naked","sweet","OGK"]'::jsonb, null, null, 35.9, true),
  (16, 'Backwoods singles', 'Backwoods', 'TOBACCO', 'Cigars & Cigarillos', 'AW-BACKWOODS-SING', 4, '["Russian cream","honey berry","sweet aromatic","original"]'::jsonb, 'backwoods_5pk.webp', null, 98.78, true),
  (17, 'B&M 25ct', 'B&M 25ct', 'TOBACCO', 'Cigars & Cigarillos', 'AW-B-M-25CT', 11, '["Regular","woodtip","sweet","sweet woodtip","casino","casino woodtip","wine","wine woodtip"]'::jsonb, 'b_m_25ct.webp', null, 39.59, true),
  (18, 'ZYN 6mg', 'ZYN 6mg', 'TOBACCO', 'Pouches & ZYN', 'AW-ZYN-6MG', 7, '["cinnamon","wintergreen","citrus","peppermint","chill","spearmint","coffee"]'::jsonb, 'zyn_6mg.webp', null, 48.98, true),
  (19, 'ZYN 3mg', 'ZYN 3mg', 'TOBACCO', 'Pouches & ZYN', 'AW-ZYN-3MG', 6, '["cinnamon","wintergreen","citrus","peppermint","chill","spearmint"]'::jsonb, 'zyn_6mg.webp', null, 50.5, true),
  (20, 'Vaseline', 'Vaseline', 'GROCERY', 'Personal Care', 'AW-VASELINE', 2, '["big","small"]'::jsonb, 'vaseline_jelly.webp', null, 26.02, true),
  (21, 'Men deodorant', 'Men deodorant', 'GROCERY', 'Personal Care', 'AW-MEN-DEODORANT', 2, '["small","big"]'::jsonb, 'men_s_deodorant.jpg', null, 19.55, true),
  (22, 'Tweaker', 'Tweaker', 'MERCHANDISE', 'OTC & Health', 'AW-TWEAKER', 7, '["berry","grape","watermelon","peach","freedom pop","tropical","sour apple"]'::jsonb, 'tweaker.webp', null, 77.22, true),
  (23, 'Tylenol', 'Tylenol', 'MERCHANDISE', 'OTC & Health', 'AW-TYLENOL', 4, '["sinus","extra","PM","cold & flu"]'::jsonb, null, null, 70.65, true),
  (24, 'Goodys', 'Goodys', 'MERCHANDISE', 'OTC & Health', 'AW-GOODYS', 7, '["2pk","6pk","red","PM","4pk orange","4pk mixed fruit","4pk hangover"]'::jsonb, null, null, 44.39, true),
  (25, 'Claritin', 'Claritin', 'MERCHANDISE', 'OTC & Health', 'AW-CLARITIN', 0, '[]'::jsonb, null, null, 38.33, true),
  (26, 'Benadryl', 'Benadryl', 'MERCHANDISE', 'OTC & Health', 'AW-BENADRYL', 0, '[]'::jsonb, null, null, 64.09, true),
  (27, 'Duracell', 'Duracell', 'MERCHANDISE', 'Electronics', 'AW-DURACELL', 7, '["9V","AAA4","AA4","D2","AAA2","AA2","C2"]'::jsonb, 'duracell_batteries.jpg', null, 38.58, true),
  (28, 'Rhino pills 2pk', 'Rhino', 'MERCHANDISE', 'Honey & Energy', 'AW-RHINO-PILLS-2P', 3, '["purple","black","gold"]'::jsonb, 'rhino_pills_2pk.webp', null, 35.55, true),
  (29, 'Carmex', 'Carmex', 'MERCHANDISE', 'Counter Goods', 'AW-CARMEX', 3, '["Tubes","jars","stick"]'::jsonb, 'carmex_tubes.webp', null, 21.91, true),
  (30, 'Visine', 'Visine', 'MERCHANDISE', 'OTC & Health', 'AW-VISINE', 0, '[]'::jsonb, null, null, 78.23, true),
  (31, 'Bic', 'Bic', 'MERCHANDISE', 'Lighters & Torches', 'AW-BIC', 5, '["mini","big","playboy","astrology","design"]'::jsonb, 'bic_lighters.jpg', 'BESTSELLER', 28.98, true),
  (32, 'Bluntpowers', 'Bluntpowers', 'MERCHANDISE', 'Counter Goods', 'AW-BLUNTPOWERS', 33, '["Cantaloupe","pineapple","polo blue","celebration","cool water","baby powder","blueberry","issey miyake"]'::jsonb, 'bluntpowers.webp', null, 55, true),
  (33, 'White R-neck', 'White', 'MERCHANDISE', 'Apparel', 'AW-WHITE-R-NECK', 9, '["S","M","L","1X","2X","3X","4X","5X"]'::jsonb, null, null, 54.74, true),
  (34, 'Black R-neck', 'Black', 'MERCHANDISE', 'Apparel', 'AW-BLACK-R-NECK', 9, '["S","M","L","1X","2X","3X","4X","5X"]'::jsonb, null, null, 39.09, true),
  (35, 'Butterfinger', 'Butterfinger', 'CANDIES', 'Chocolate Bars', 'AW-BUTTERFINGER', 2, '["king size","regular"]'::jsonb, 'butterfinger_regular.jpg', null, 32.8, true),
  (36, 'Now and later', 'Now and', 'CANDIES', 'Sweets & Gummies', 'AW-NOW-AND-LATER', 6, '["grape","green apple","tropical punch","watermelon","cherry","strawberry"]'::jsonb, 'now_later.jpg', null, 34.32, true),
  (37, 'Airheads 36ct', 'Airheads', 'CANDIES', 'Sweets & Gummies', 'AW-AIRHEADS-36CT', 6, '["sour blue","white mystery","watermelon","blue","cherry","orange"]'::jsonb, 'airheads_36ct.webp', null, 21.41, true),
  (38, 'Wriggly slim pack', 'Wriggly', 'CANDIES', 'Sweets & Gummies', 'AW-WRIGGLY-SLIM-P', 5, '["spearmint","doublemint","winterfresh","big red","juicy fruity"]'::jsonb, null, null, 25.4, true),
  (39, 'Ferrara', 'Ferrara', 'CANDIES', 'Sweets & Gummies', 'AW-FERRARA', 2, '["Lemonheads","BBB"]'::jsonb, 'ferrara_bbb.webp', null, 40.98, true),
  (40, 'Wriggly 50¢', 'Wriggly', 'CANDIES', 'Sweets & Gummies', 'AW-WRIGGLY-50', 3, '["spearmint","double mint","juicy fruit"]'::jsonb, 'wriggly_50c.webp', null, 38.66, true),
  (41, 'Trident', 'Trident', 'CANDIES', 'Gum & Mints', 'AW-TRIDENT', 4, '["wintergreen","spearmint","peppermint","tropical"]'::jsonb, null, null, 14.6, true),
  (42, 'Orbit', 'Orbit', 'CANDIES', 'Gum & Mints', 'AW-ORBIT', 3, '["sweet mint","peppermint","spearmint"]'::jsonb, null, null, 10.86, true),
  (43, 'Mentos', 'Mentos', 'CANDIES', 'Gum & Mints', 'AW-MENTOS', 3, '["strawberry","mint","fruit"]'::jsonb, 'mentos.webp', null, 34.68, true),
  (44, 'Mike & Ike', 'Mike', 'CANDIES', 'Sweets & Gummies', 'AW-MIKE-IKE', 7, '["watermelon","grape","blue raspberry","sour blue","green","cherry","blue"]'::jsonb, 'mike_ike.webp', null, 38.79, true),
  (45, 'Argo corn starch', 'Argo', 'FOOD STUFF', 'Cooking Basics', 'AW-ARGO-CORN-STAR', 0, '[]'::jsonb, 'argo_corn_starch.webp', null, 20.5, true),
  (46, 'Imperial sugar', 'Imperial', 'FOOD STUFF', 'Cooking Basics', 'AW-IMPERIAL-SUGAR', 2, '["small","big"]'::jsonb, 'imperial_sugar.webp', null, 42.52, true),
  (47, 'Cheezit', 'Cheezit', 'FOOD STUFF', 'Chips & Crackers', 'AW-CHEEZIT', 4, '["extra bold","white cheddar","original","hot & spicy"]'::jsonb, 'cheezit.jpg', null, 28.98, true),
  (48, 'Ritz', 'Ritz', 'FOOD STUFF', 'Chips & Crackers', 'AW-RITZ', 3, '["peanut butter","cheese","original"]'::jsonb, null, null, 23.53, true),
  (49, 'Pop tarts', 'Pop tarts', 'FOOD STUFF', 'Chips & Crackers', 'AW-POP-TARTS', 3, '["strawberry","s''mores","brown sugar cinnamon"]'::jsonb, 'pop_tarts.webp', null, 25.95, true),
  (50, 'Clover hill', 'Clover', 'FOOD STUFF', 'Quick Meals', 'AW-CLOVER-HILL', 2, '["big Texas","honey bun"]'::jsonb, null, null, 44.94, true),
  (51, 'Cereal cups', 'Cereal', 'FOOD STUFF', 'Quick Meals', 'AW-CEREAL-CUPS', 4, '["Frosted Flakes","Apple jack","Froot Loops","Corn Pops"]'::jsonb, 'cereal_cups.jpg', null, 30, true),
  (52, 'Gurleys', 'Gurleys', 'FOOD STUFF', 'Cookies', 'AW-GURLEYS', 4, '["butter flies","circus peanuts","watermelon rings","gummy worms"]'::jsonb, null, null, 21.31, true),
  (53, 'Glass cleaner', 'Glass', 'GROCERY', 'Cleaning', 'AW-GLASS-CLEANER', 2, '["oxy power","original"]'::jsonb, null, null, 6.82, true),
  (54, 'Stay free pads', 'Stay', 'GROCERY', 'Personal Care', 'AW-STAY-FREE-PADS', 3, '["Small","Medium","big"]'::jsonb, null, null, 14.9, true),
  (55, 'STP', 'STP', 'MOTOR OIL', 'Motor Oil', 'AW-STP', 9, '["black","octane","red","White fuel injector","water remover","silver","power steering","brake fluid"]'::jsonb, 'stp_oil_treatment.webp', 'BESTSELLER', 41.17, true),
  (56, 'Saxon', 'Saxon', 'MOTOR OIL', 'Motor Oil', 'AW-SAXON', 10, '["5w30","5w20","10w30","10w40","20w50","Type A","Type F","Multipurpose"]'::jsonb, 'saxon_motor_oil.png', 'BESTSELLER', 44.2, true),
  (57, 'Pure guard', 'Pure', 'MOTOR OIL', 'Motor Oil', 'AW-PURE-GUARD', 3, '["5w30","10w30","10w40"]'::jsonb, null, null, 43.83, true),
  (58, 'Faygo bottles', 'Faygo', 'DRINKS & BAGS', 'Sodas', 'AW-FAYGO-BOTTLES', 9, '["redpop","rock & rye","orange","grape","cotton candy","peach","fireworks","moon mist"]'::jsonb, 'faygo_bottles_20oz.jpg', null, 18.64, true),
  (59, 'Arizona', 'Arizona', 'DRINKS & BAGS', 'Juices & Teas', 'AW-ARIZONA', 10, '["RX","strawberry kiwi","watermelon","frosty chill","tropical chill","green tea","fruit punch","orange"]'::jsonb, 'arizona.webp', null, 13.14, true),
  (60, 'Geekbar 15K', 'Geekbar', 'NOVELTIES', 'Disposable Vapes', 'AW-GEEKBAR-15K', 2, '["Blue razz ice","Fuckin fab"]'::jsonb, 'geekbar_15k.webp', 'BESTSELLER', 43.23, true),
  (61, 'Geekbar 25K', 'Geekbar', 'NOVELTIES', 'Disposable Vapes', 'AW-GEEKBAR-25K', 2, '["Sour straws","sour mango pineapple"]'::jsonb, 'geekbar_25k_pulse.webp', 'BESTSELLER', 38.18, true),
  (62, 'Foger Full kit', 'Foger', 'NOVELTIES', 'Disposable Vapes', 'AW-FOGER-FULL-KIT', 28, '["Coconut cupcake","Strawberry kiwi","Red velvet cupcake","Watermelon ice Kiwi dragon berry","Mexico mango","Omg b burst","White gummy","Blue rancher"]'::jsonb, 'foger_full_kit.jpg', 'NEW', 44.24, true),
  (63, 'Foger Pods', 'Foger', 'NOVELTIES', 'Vape Pods', 'AW-FOGER-PODS', 26, '["Sour Apple ice","Vanilla ice cream","Pineapple coconut","Kiwi dragon berry","White gummy","California cherry","Strawberry watermelon","Strawberry ice"]'::jsonb, 'foger_pods.webp', null, 91.71, true),
  (64, 'RAZ 25K', 'RAZ 25K', 'NOVELTIES', 'Disposable Vapes', 'AW-RAZ-25K', 0, '[]'::jsonb, null, 'NEW', 55.35, true),
  (65, 'RAZ Vue Full kit', 'RAZ Vue', 'NOVELTIES', 'Disposable Vapes', 'AW-RAZ-VUE-FULL-K', 0, '[]'::jsonb, null, null, 114.94, true),
  (66, 'RAZ Vue Pods', 'RAZ Vue', 'NOVELTIES', 'Vape Pods', 'AW-RAZ-VUE-PODS', 0, '[]'::jsonb, null, null, 88.68, true),
  (67, 'Kang 8000', 'Kang', 'NOVELTIES', 'Disposable Vapes', 'AW-KANG-8000', 0, '[]'::jsonb, 'kang_vape_65k.jpg', null, 51.31, true),
  (68, 'Kang 65K', 'Kang', 'NOVELTIES', 'Disposable Vapes', 'AW-KANG-65K', 0, '[]'::jsonb, 'kang_vape_65k.jpg', null, 58.38, true),
  (69, 'Shroom Puff disposable 3 Gram', 'Shroom', 'NOVELTIES', 'Mushroom Products', 'AW-SHROOM-PUFF-DI', 5, '["Blue","watermelon","strawberry","pineapple","green"]'::jsonb, null, null, 59.39, true),
  (70, 'Shroom Puff Pre rolls 2pk', 'Shroom', 'NOVELTIES', 'Mushroom Products', 'AW-SHROOM-PUFF-PR', 0, '[]'::jsonb, null, null, 62.42, true),
  (71, 'Shroom Puff pre rolls jars', 'Shroom', 'NOVELTIES', 'Mushroom Products', 'AW-SHROOM-PUFF-PR', 0, '[]'::jsonb, null, null, 28.08, true),
  (72, 'Shroom puff Gummies', 'Shroom', 'NOVELTIES', 'Mushroom Products', 'AW-SHROOM-PUFF-GU', 0, '[]'::jsonb, null, null, 32.12, true),
  (73, 'Mental Health disposable 4 gram', 'Mental', 'NOVELTIES', 'Mushroom Products', 'AW-MENTAL-HEALTH-', 0, '[]'::jsonb, null, null, 112.92, true),
  (74, 'Mental Health pre rolls 2pk', 'Mental', 'NOVELTIES', 'Mushroom Products', 'AW-MENTAL-HEALTH-', 3, '["Purple dragon","strawberry","blueberry"]'::jsonb, null, null, 48.28, true),
  (75, 'Wava kava', 'Wava', 'NOVELTIES', 'Kratom & Kava', 'AW-WAVA-KAVA', 4, '["Blueberry","strawberry banana","mango","assorted"]'::jsonb, null, 'NEW', 112.92, true),
  (76, 'Mazza Shots', 'Mazza', 'NOVELTIES', 'Kratom & Kava', 'AW-MAZZA-SHOTS', 4, '["Purple","ruby","yellow","assorted"]'::jsonb, null, 'NEW', 95.75, true),
  (77, 'Slapwoods 5pk', 'Slapwoods', 'TOBACCO', 'Cigars & Cigarillos', 'AW-SLAPWOODS-5PK', 6, '["Russian cream","natural","sweet","banana","bloodshot","Black Russian"]'::jsonb, 'slapwoods_5pk.webp', null, 43.98, true),
  (78, 'B&M 5pk', 'B&M 5pk', 'TOBACCO', 'Cigars & Cigarillos', 'AW-B-M-5PK', 10, '["regular","woodtip","select","wine","wine woodtip","cream","apple","jazz"]'::jsonb, 'b_m_5pk.jpg', null, 24.99, true),
  (79, 'Game leaf 3pk', 'Game', 'TOBACCO', 'Wraps & Leafs', 'AW-GAME-LEAF-3PK', 3, '["Russian cream","natural","cognac"]'::jsonb, 'game_leaf_3pk.jpg', null, 87.37, true),
  (80, 'SS wraps', 'SS wraps', 'TOBACCO', 'Wraps & Leafs', 'AW-SS-WRAPS', 3, '["Red","peach","Irish cream"]'::jsonb, 'ss_wraps.webp', null, 104.69, true),
  (81, 'SS twin pack', 'SS twin', 'TOBACCO', 'Cigars & Cigarillos', 'AW-SS-TWIN-PACK', 4, '["Mini diamond","mini red","red","diamond"]'::jsonb, 'ss_twin_pack_mini.jpg', null, 25.6, true),
  (82, 'Pompom', 'Pompom', 'TOBACCO', 'Cigars & Cigarillos', 'AW-POMPOM', 2, '["Red","green"]'::jsonb, 'pompom.jpg', 'DEAL', 40, true),
  (83, 'Dutch master', 'Dutch', 'TOBACCO', 'Cigars & Cigarillos', 'AW-DUTCH-MASTER', 11, '["Gold","honey","Java","blue","diamond","silver","Irish fusion","OG fusion"]'::jsonb, 'dutch_master.jpg', null, 71.51, true),
  (84, 'Good times flat wraps', 'Good', 'TOBACCO', 'Wraps & Leafs', 'AW-GOOD-TIMES-FLA', 7, '["Natural","diamond","vanilla","fruit punch","mango","strawberry kiwi","chocolate"]'::jsonb, 'good_times_flat_wraps.jpg', null, 41.36, true),
  (85, 'Zigzag Wraps', 'Zigzag', 'TOBACCO', 'Wraps & Leafs', 'AW-ZIGZAG-WRAPS', 4, '["Straight up","grape","melon","mango"]'::jsonb, 'zigzag_wraps.webp', null, 38.48, true),
  (86, 'Seneca', 'Seneca', 'TOBACCO', 'Cigarettes', 'AW-SENECA', 8, '["Menthol 100","menthol short","red 100","red short","silver 100","silver short","blue 100","blue short"]'::jsonb, 'seneca_120.png', null, 63.88, true),
  (87, 'Old tyme', 'Old tyme', 'DRINKS & BAGS', 'Sodas', 'AW-OLD-TYME', 14, '["Fruit punch","blue","mango","pineapple","grape","purple passion","pina colada","strawberry kiwi"]'::jsonb, null, null, 32.08, true),
  (88, 'Tropical Fantasy', 'Tropical', 'DRINKS & BAGS', 'Juices & Teas', 'AW-TROPICAL-FANTA', 11, '["Blue","fruit punch","grape","pineapple","strawberry lemonade","kiwi strawberry","green","lemonade"]'::jsonb, null, null, 15.34, true),
  (89, 'Faygo cans', 'Faygo', 'DRINKS & BAGS', 'Sodas', 'AW-FAYGO-CANS', 14, '["Cola","fruit punch","redpop","pineapple","peach","kiwi strawberry","moon mist","lemon twist"]'::jsonb, 'faygo_bottles_20oz.jpg', null, 47.92, true),
  (90, 'Bags', 'Bags', 'DRINKS & BAGS', 'Bags & Carriers', 'AW-BAGS', 3, '["1/6","1/8","1/10"]'::jsonb, 'haribo_bags.webp', null, 47.97, true),
  (91, 'Paper bags', 'Paper', 'DRINKS & BAGS', 'Bags & Carriers', 'AW-PAPER-BAGS', 3, '["#1","#2","#4"]'::jsonb, 'paper_bags_2.webp', null, 40.55, true),
  (92, 'Register papers', 'Register', 'DRINKS & BAGS', 'Bags & Carriers', 'AW-REGISTER-PAPER', 5, '["Big","small","EBT","credit card","fuel pump"]'::jsonb, null, null, 38.09, true),
  (93, '6pk beer carriers', '6pk beer', 'DRINKS & BAGS', 'Bags & Carriers', 'AW-6PK-BEER-CARRI', 0, '[]'::jsonb, null, null, 30.39, true),
  (94, 'Beer ringers', 'Beer', 'DRINKS & BAGS', 'Bags & Carriers', 'AW-BEER-RINGERS', 0, '[]'::jsonb, null, null, 31.75, true),
  (95, 'Trash can liners', 'Trash', 'DRINKS & BAGS', 'Bags & Carriers', 'AW-TRASH-CAN-LINE', 0, '[]'::jsonb, null, null, 23.51, true),
  (96, 'Autoguard', 'Autoguard', 'MOTOR OIL', 'Motor Oil', 'AW-AUTOGUARD', 3, '["Power steering","brake fluid","antifreeze"]'::jsonb, 'autoguard_brake_fluid.webp', null, 44.36, true),
  (97, '2-cycle oil', '2-cycle', 'MOTOR OIL', 'Lubricants', 'AW-2-CYCLE-OIL', 0, '[]'::jsonb, '2_cycle_oil.webp', null, 38.22, true),
  (98, 'DEF 2.5 gal', 'DEF 2.5', 'MOTOR OIL', 'Fluids', 'AW-DEF-2-5-GAL', 0, '[]'::jsonb, 'blue_def_2_5_gal.jpg', null, 12.2, true),
  (99, 'Peak antifreeze', 'Peak', 'MOTOR OIL', 'Fluids', 'AW-PEAK-ANTIFREEZ', 0, '[]'::jsonb, 'peak_antifreeze.webp', null, 38.5, true),
  (100, 'Cheap antifreeze', 'Cheap', 'MOTOR OIL', 'Fluids', 'AW-CHEAP-ANTIFREE', 0, '[]'::jsonb, null, null, 28.08, true),
  (101, 'GTX Castrol', 'GTX Castrol', 'MOTOR OIL', 'Motor Oil', 'AW-GTX-CASTROL', 5, '["5w30","5w20","10w30","10w40","20w50"]'::jsonb, 'gtx_castrol.jpg', null, 18.7, true),
  (102, 'Havoline', 'Havoline', 'MOTOR OIL', 'Motor Oil', 'AW-HAVOLINE', 5, '["5w30","5w20","10w30","10w40","20w50"]'::jsonb, 'havoline.webp', null, 29.05, true),
  (103, 'Windshield washer', 'Windshield', 'MOTOR OIL', 'Fluids', 'AW-WINDSHIELD-WAS', 0, '[]'::jsonb, 'windshield_washer_2.webp', null, 19.87, true),
  (104, 'Tire inflators', 'Tire', 'MOTOR OIL', 'Auto Accessories', 'AW-TIRE-INFLATORS', 2, '["With hose","without hose"]'::jsonb, 'tire_fixer_with_hose.jpg', null, 52.68, true),
  (105, 'WD-40', 'WD-40', 'MOTOR OIL', 'Lubricants', 'AW-WD-40', 2, '["Big","small"]'::jsonb, 'wd_40_big.jpg', 'DEAL', 31.95, true),
  (106, 'Sandwich bags', 'Sandwich', 'GROCERY', 'Bags & Storage', 'AW-SANDWICH-BAGS', 2, '["Homesmart","Goodsense"]'::jsonb, 'sandwich_bags.webp', null, 21.57, true),
  (107, 'Trash bags', 'Trash', 'GROCERY', 'Bags & Storage', 'AW-TRASH-BAGS', 4, '["13gal","23gal","kitchen","lawn"]'::jsonb, null, null, 17.05, true),
  (108, 'Tampax', 'Tampax', 'GROCERY', 'Personal Care', 'AW-TAMPAX', 2, '["Yellow","green"]'::jsonb, 'tampax.webp', null, 8.2, true),
  (109, 'Ajax Dishwasher', 'Ajax', 'GROCERY', 'Cleaning', 'AW-AJAX-DISHWASHE', 6, '["Blue","red","yellow","orange","green","purple"]'::jsonb, null, null, 39.47, true),
  (110, 'Brillo dishwasher', 'Brillo', 'GROCERY', 'Cleaning', 'AW-BRILLO-DISHWAS', 5, '["Blue","yellow","orange","yellow","green"]'::jsonb, 'brillo_dishwasher.png', null, 33.13, true),
  (111, 'Tide liquid', 'Tide', 'GROCERY', 'Laundry & Detergent', 'AW-TIDE-LIQUID', 2, '["Big","small"]'::jsonb, 'tide.jpg', null, 16.36, true),
  (112, 'Gain liquid', 'Gain', 'GROCERY', 'Laundry & Detergent', 'AW-GAIN-LIQUID', 2, '["Big","small"]'::jsonb, 'gain.jpg', null, 18.02, true),
  (113, 'Clorox', 'Clorox', 'GROCERY', 'Cleaning', 'AW-CLOROX', 3, '["Big","medium","small"]'::jsonb, null, null, 18.86, true),
  (114, 'Ajax bleach', 'Ajax', 'GROCERY', 'Cleaning', 'AW-AJAX-BLEACH', 0, '[]'::jsonb, 'ajax_bleach.jpg', null, 32.92, true),
  (115, 'Dove soap', 'Dove', 'GROCERY', 'Personal Care', 'AW-DOVE-SOAP', 1, '["Original"]'::jsonb, 'dove_soap.jpg', null, 30.74, true),
  (116, 'Irish spring soap', 'Irish', 'GROCERY', 'Personal Care', 'AW-IRISH-SPRING-S', 0, '[]'::jsonb, 'irish_spring_soap.jpg', null, 39.19, true),
  (117, 'Awesome laundry', 'Awesome', 'GROCERY', 'Cleaning', 'AW-AWESOME-LAUNDR', 2, '["Red","orange"]'::jsonb, null, null, 4.76, true),
  (118, 'Foam plates', 'Foam', 'GROCERY', 'Paper & Plastic', 'AW-FOAM-PLATES', 2, '["Big","small"]'::jsonb, null, null, 6.02, true),
  (119, 'Foam bowls', 'Foam', 'GROCERY', 'Paper & Plastic', 'AW-FOAM-BOWLS', 0, '[]'::jsonb, null, null, 29.73, true),
  (120, 'Foam cups', 'Foam', 'GROCERY', 'Paper & Plastic', 'AW-FOAM-CUPS', 4, '["20oz","16oz","12oz","8oz"]'::jsonb, 'foam_cups.jpg', null, 35.39, true),
  (121, 'Plastic', 'Plastic', 'GROCERY', 'Paper & Plastic', 'AW-PLASTIC', 3, '["Spoons","forks","Assorted cutlery"]'::jsonb, null, null, 36.52, true),
  (122, '4pk tissues', '4pk tissues', 'GROCERY', 'Paper & Plastic', 'AW-4PK-TISSUES', 1, '["Case"]'::jsonb, '4pk_tissues.avif', null, 10.34, true),
  (123, 'Paper towels', 'Paper', 'GROCERY', 'Paper & Plastic', 'AW-PAPER-TOWELS', 1, '["Case"]'::jsonb, 'paper_towels.jpg', null, 31.87, true),
  (124, 'Single tissues', 'Single', 'GROCERY', 'Paper & Plastic', 'AW-SINGLE-TISSUES', 1, '["Case"]'::jsonb, 'single_tissues.jpg', null, 28.56, true),
  (125, 'Baby diapers', 'Baby', 'GROCERY', 'Personal Care', 'AW-BABY-DIAPERS', 3, '["Big","small","medium"]'::jsonb, null, null, 36.24, true),
  (126, 'Baby wipes', 'Baby', 'GROCERY', 'Personal Care', 'AW-BABY-WIPES', 2, '["Boys","girls"]'::jsonb, null, null, 19.19, true),
  (127, 'Drain opener', 'Drain', 'GROCERY', 'Cleaning', 'AW-DRAIN-OPENER', 0, '[]'::jsonb, null, null, 13.61, true),
  (128, 'Fabulouso', 'Fabulouso', 'GROCERY', 'Cleaning', 'AW-FABULOUSO', 2, '["Small","big"]'::jsonb, 'fabulouso.avif', null, 23.51, true),
  (129, 'Home air fresheners', 'Home', 'GROCERY', 'Other Grocery', 'AW-HOME-AIR-FRESH', 0, '[]'::jsonb, null, null, 37.17, true),
  (130, 'Brillo basics all purpose cleaner', 'Brillo', 'GROCERY', 'Cleaning', 'AW-BRILLO-BASICS-', 4, '["Yellow","orange","purple","brown"]'::jsonb, null, null, 38.94, true),
  (131, 'Matches', 'Matches', 'GROCERY', 'Hardware', 'AW-MATCHES', 2, '["Small","big"]'::jsonb, null, null, 30.46, true),
  (132, 'Charcoal bags small', 'Charcoal', 'GROCERY', 'Hardware', 'AW-CHARCOAL-BAGS-', 2, '["White","red"]'::jsonb, null, null, 30.14, true),
  (133, 'Charcoal bags big', 'Charcoal', 'GROCERY', 'Hardware', 'AW-CHARCOAL-BAGS-', 2, '["White","red"]'::jsonb, null, null, 9.77, true),
  (134, 'Rubbing alcohol', 'Rubbing', 'GROCERY', 'Personal Care', 'AW-RUBBING-ALCOHO', 2, '["White","green"]'::jsonb, null, null, 16.08, true),
  (135, 'Hydro peroxide', 'Hydro', 'GROCERY', 'Personal Care', 'AW-HYDRO-PEROXIDE', 0, '[]'::jsonb, null, null, 7.71, true),
  (136, 'Always pads', 'Always', 'GROCERY', 'Personal Care', 'AW-ALWAYS-PADS', 3, '["Big","medium","small"]'::jsonb, null, null, 12.84, true),
  (137, 'Nail clippers', 'Nail', 'GROCERY', 'Hardware', 'AW-NAIL-CLIPPERS', 2, '["Big","small"]'::jsonb, null, null, 27.51, true),
  (138, 'Charcoal lighter fluid', 'Charcoal', 'GROCERY', 'Hardware', 'AW-CHARCOAL-LIGHT', 2, '["Big","small"]'::jsonb, null, null, 10.7, true),
  (139, 'Vinut', 'Vinut', 'DRINKS & BAGS', 'Juices & Teas', 'AW-VINUT', 8, '["Watermelon","pineapple","mango","soursop","passion fruit","cranberry","apple","orange"]'::jsonb, null, null, 23.43, true),
  (140, 'Tropicana small', 'Tropicana', 'DRINKS & BAGS', 'Juices & Teas', 'AW-TROPICANA-SMAL', 6, '["Orange","pineapple orange","grape","cranberry","kiwi strawberry lemonade","ruby red"]'::jsonb, null, null, 48.04, true),
  (141, 'Tropical Fantasy Aloe Vera', 'Tropical', 'DRINKS & BAGS', 'Juices & Teas', 'AW-TROPICAL-FANTA', 6, '["Watermelon","strawberry","mango","peach","pineapple","original"]'::jsonb, null, null, 37.78, true),
  (142, 'Calypso', 'Calypso', 'DRINKS & BAGS', 'Juices & Teas', 'AW-CALYPSO', 4, '["Tropical mango","original","paradise punch","kiwi lemonade"]'::jsonb, null, null, 24.25, true),
  (143, 'Red Bull 12oz', 'Red Bull', 'DRINKS & BAGS', 'Energy Drinks', 'AW-RED-BULL-12OZ', 11, '["Regular","watermelon","yellow","white peach","wild berries","green","white","sugar free"]'::jsonb, null, 'BESTSELLER', 27.96, true),
  (144, 'Redbull 8oz', 'Redbull', 'DRINKS & BAGS', 'Other Drinks', 'AW-REDBULL-8OZ', 11, '["Regular","watermelon","yellow","white peach","wild berries","green","white","sugar free"]'::jsonb, null, null, 43.47, true),
  (145, 'Redbull 16oz', 'Redbull', 'DRINKS & BAGS', 'Other Drinks', 'AW-REDBULL-16OZ', 0, '[]'::jsonb, null, null, 41.17, true),
  (146, 'Redbull 20oz', 'Redbull', 'DRINKS & BAGS', 'Other Drinks', 'AW-REDBULL-20OZ', 0, '[]'::jsonb, null, null, 40.23, true),
  (147, 'Magnum', 'Magnum', 'MERCHANDISE', 'Adult Wellness', 'AW-MAGNUM', 10, '["Regular","XL","bareskin","thin","ecstasy","Raw","Discovery pack","Jar big"]'::jsonb, 'magnum.jpg', null, 60.8, true),
  (148, 'Trojan', 'Trojan', 'MERCHANDISE', 'Adult Wellness', 'AW-TROJAN', 7, '["Bareskin","ultra thin","ecstasy","her pleasure","Pleasure pack","G spot","double ecstasy"]'::jsonb, 'trojan.webp', null, 29.49, true),
  (149, 'Rolling dice', 'Rolling', 'MERCHANDISE', 'Counter Goods', 'AW-ROLLING-DICE', 3, '["Big","small","colored"]'::jsonb, null, null, 5, true),
  (150, 'Cables', 'Cables', 'MERCHANDISE', 'Electronics', 'AW-CABLES', 12, '["iPhone","Type C","Android","Car charger","home charger","iPhone To type C","Type C To Type C","Home charger with type C"]'::jsonb, null, null, 64.59, true),
  (151, 'White V-neck', 'White', 'MERCHANDISE', 'Apparel', 'AW-WHITE-V-NECK', 9, '["S","M","L","1X","2X","3X","4X","5X"]'::jsonb, null, null, 51.96, true),
  (152, 'Black V-neck:', 'Black', 'MERCHANDISE', 'Apparel', 'AW-BLACK-V-NECK', 9, '["S","M","L","1X","2X","3X","4X","5X"]'::jsonb, null, null, 26.71, true),
  (153, 'White Long Sleeve', 'White', 'MERCHANDISE', 'Apparel', 'AW-WHITE-LONG-SLE', 9, '["S","M","L","1X","2X","3X","4X","5X"]'::jsonb, null, null, 26.96, true),
  (154, 'Black Long Sleeve', 'Black', 'MERCHANDISE', 'Apparel', 'AW-BLACK-LONG-SLE', 9, '["S","M","L","1X","2X","3X","4X","5X"]'::jsonb, null, null, 50.45, true),
  (155, 'White Thermals', 'White', 'MERCHANDISE', 'Apparel', 'AW-WHITE-THERMALS', 9, '["S","M","L","1X","2X","3X","4X","5X"]'::jsonb, null, null, 28.48, true),
  (156, 'Black Thermals', 'Black', 'MERCHANDISE', 'Apparel', 'AW-BLACK-THERMALS', 9, '["S","M","L","1X","2X","3X","4X","5X"]'::jsonb, null, null, 37.57, true),
  (157, 'Winterhats', 'Winterhats', 'MERCHANDISE', 'Apparel', 'AW-WINTERHATS', 7, '["Black","white","grey","red","blue","green","purple"]'::jsonb, null, null, 70.65, true),
  (158, 'Socks', 'Socks', 'MERCHANDISE', 'Apparel', 'AW-SOCKS', 2, '["White","black"]'::jsonb, null, null, 54.49, true),
  (159, 'Little trees', 'Little', 'MERCHANDISE', 'Air Fresheners & Incense', 'AW-LITTLE-TREES', 3, '["Assorted display","black ice single","black ice pack"]'::jsonb, null, null, 17.12, true),
  (160, 'A-Shirt White', 'A-Shirt', 'MERCHANDISE', 'Apparel', 'AW-A-SHIRT-WHITE', 9, '["S","M","L","1X","2X","3X","4X","5X"]'::jsonb, null, null, 8.78, true),
  (161, 'A-Shirts Black', 'A-Shirts', 'MERCHANDISE', 'Apparel', 'AW-A-SHIRTS-BLACK', 9, '["S","M","L","1X","2X","3X","4X","5X"]'::jsonb, null, null, 76.71, true),
  (162, 'Snickers', 'Snickers', 'CANDIES', 'Chocolate Bars', 'AW-SNICKERS', 4, '["Regular","King size","Almond reg","almond king size"]'::jsonb, 'snickers_almond_share.webp', 'BESTSELLER', 34.05, true),
  (163, 'M&M’s', 'M&M’s', 'CANDIES', 'Chocolate Bars', 'AW-M-M-S', 4, '["Yellow reg","yellow share size","chocolate reg","chocolate king size"]'::jsonb, 'm_m_s_chocolate_share.jpg', null, 24.14, true),
  (164, 'KitKat', 'KitKat', 'CANDIES', 'Chocolate Bars', 'AW-KITKAT', 4, '["Regular","King size","vanilla reg","vanilla king size"]'::jsonb, 'kitkat_king_size.webp', null, 14.38, true),
  (165, 'Twix', 'Twix', 'CANDIES', 'Chocolate Bars', 'AW-TWIX', 2, '["Regular","king size"]'::jsonb, 'twix_regular.webp', null, 23.08, true),
  (166, 'Reese’s', 'Reese’s', 'CANDIES', 'Chocolate Bars', 'AW-REESE-S', 12, '["Cups regular","cups king size","white cups reg","white cups king size","pieces reg","pieces king size","fast break reg","fast break king size"]'::jsonb, 'reese_s.jpg', 'BESTSELLER', 29.2, true),
  (167, 'Almond joy', 'Almond', 'CANDIES', 'Chocolate Bars', 'AW-ALMOND-JOY', 2, '["Regular","king size"]'::jsonb, 'almond_joy_3.jpg', null, 23.23, true),
  (168, 'Mounds', 'Mounds', 'CANDIES', 'Chocolate Bars', 'AW-MOUNDS', 2, '["Regular","king size"]'::jsonb, 'mounds_bar_king_size.jpg', null, 36.65, true),
  (169, 'Skittles', 'Skittles', 'CANDIES', 'Sweets & Gummies', 'AW-SKITTLES', 10, '["Red reg","red king size","wildberry reg","wildberry king size","sour reg","sour king size","blue reg","blue king size"]'::jsonb, 'skittles.jpg', 'BESTSELLER', 26.1, true),
  (170, 'Payday', 'Payday', 'CANDIES', 'Chocolate Bars', 'AW-PAYDAY', 2, '["Regular","king size"]'::jsonb, 'payday_king_size.jpg', null, 14.47, true),
  (171, 'Hershey', 'Hershey', 'CANDIES', 'Chocolate Bars', 'AW-HERSHEY', 8, '["Milk reg","milk king size","cookies reg","cookies king","almond reg","almond king","Mr. Goodbar reg","Mr. Goodbar king"]'::jsonb, 'hershey.jpg', 'BESTSELLER', 22.11, true),
  (172, '3-musketeers', '3-musketeers', 'CANDIES', 'Chocolate Bars', 'AW-3-MUSKETEERS', 2, '["Regular","king size"]'::jsonb, '3_musketeers_regular.webp', null, 12.07, true),
  (173, 'Rip Rolls', 'Rip Rolls', 'CANDIES', 'Sweets & Gummies', 'AW-RIP-ROLLS', 7, '["Strawberry","green apple","rainbow","blue","grape","cherry","watermelon"]'::jsonb, 'rip_rolls.webp', null, 43.94, true),
  (174, 'Longboy Jar', 'Longboy', 'CANDIES', 'Jars', 'AW-LONGBOY-JAR', 0, '[]'::jsonb, 'longboy_jar.webp', null, 17.17, true),
  (175, 'Chico-stick Jar', 'Chico-stick', 'CANDIES', 'Jars', 'AW-CHICO-STICK-JA', 0, '[]'::jsonb, 'chico_stick_jar.webp', null, 17.8, true),
  (176, 'PB jar', 'PB jar', 'CANDIES', 'Jars', 'AW-PB-JAR', 0, '[]'::jsonb, 'pb_jar.jpg', null, 35.68, true),
  (177, 'Haribo Jar', 'Haribo', 'CANDIES', 'Jars', 'AW-HARIBO-JAR', 0, '[]'::jsonb, 'haribo_jar.jpg', null, 37.85, true),
  (178, 'Sour punch Jar', 'Sour', 'CANDIES', 'Jars', 'AW-SOUR-PUNCH-JAR', 2, '["Small","big"]'::jsonb, 'sour_punch_jar.webp', null, 21.59, true),
  (179, 'Laffy taffy Jar', 'Laffy', 'CANDIES', 'Jars', 'AW-LAFFY-TAFFY-JA', 4, '["Assorted","blue","banana","green apple"]'::jsonb, 'laffy_taffy_bucket.webp', null, 40.4, true),
  (180, 'Laffy taffy ropes', 'Laffy', 'CANDIES', 'Sweets & Gummies', 'AW-LAFFY-TAFFY-RO', 7, '["White mystery","blue","banana","cherry","strawberry","green apple","grape"]'::jsonb, 'laffy_taffy_ropes.webp', null, 18.27, true),
  (181, 'Sour straws', 'Sour', 'CANDIES', 'Sweets & Gummies', 'AW-SOUR-STRAWS', 2, '["Blue raspberry","rainbow"]'::jsonb, 'sour_power_straws.jpg', null, 31.53, true),
  (182, 'Sour punch', 'Sour', 'CANDIES', 'Sweets & Gummies', 'AW-SOUR-PUNCH', 5, '["Blue raspberry","strawberry","watermelon","grape","rainbow"]'::jsonb, 'sour_punch_jar.webp', null, 24.28, true),
  (183, 'Extra Gum', 'Extra', 'CANDIES', 'Gum & Mints', 'AW-EXTRA-GUM', 5, '["Watermelon","spearmint","peppermint","polar ice","winter fresh"]'::jsonb, null, null, 24.15, true),
  (184, 'Tueni', 'Tueni', 'CANDIES', 'Sweets & Gummies', 'AW-TUENI', 11, '["Lemon","tropical","blue raspberry","green apple","mango","pineapple","banana","grape"]'::jsonb, 'tueni_chews.jpg', 'NEW', 26.68, true),
  (185, 'Frooties', 'Frooties', 'CANDIES', 'Sweets & Gummies', 'AW-FROOTIES', 0, '[]'::jsonb, 'frooties.webp', null, 22.83, true),
  (186, 'Blowpop', 'Blowpop', 'CANDIES', 'Sweets & Gummies', 'AW-BLOWPOP', 5, '["Regular","blue razz","black cherry","watermelon","caramel apple"]'::jsonb, 'blowpop.webp', null, 23.84, true),
  (187, 'Gusher box', 'Gusher', 'CANDIES', 'Sweets & Gummies', 'AW-GUSHER-BOX', 1, '["Regular"]'::jsonb, 'gushers_box.webp', null, 42.63, true),
  (188, 'Nerds pouch', 'Nerds', 'CANDIES', 'Sweets & Gummies', 'AW-NERDS-POUCH', 3, '["Red","blue","cherry lemonade"]'::jsonb, 'nerds_pouches_1.webp', null, 20.77, true),
  (189, 'Mamba Big bar', 'Mamba', 'CANDIES', 'Sweets & Gummies', 'AW-MAMBA-BIG-BAR', 3, '["Original","sour","tropical"]'::jsonb, 'mamba_big_bars.jpg', null, 16.04, true),
  (190, 'Mamba small', 'Mamba', 'CANDIES', 'Sweets & Gummies', 'AW-MAMBA-SMALL', 3, '["Regular","tropical","sour"]'::jsonb, 'mamba_big_bars.jpg', null, 43.6, true),
  (191, 'Mint lumps', 'Mint', 'CANDIES', 'Sweets & Gummies', 'AW-MINT-LUMPS', 0, '[]'::jsonb, 'mint_lumps.jpg', null, 32.23, true),
  (192, 'Cherry lumps', 'Cherry', 'CANDIES', 'Sweets & Gummies', 'AW-CHERRY-LUMPS', 0, '[]'::jsonb, 'cherry_lumps.jpg', null, 18.58, true),
  (193, 'Pure eyes', 'Pure', 'MERCHANDISE', 'OTC & Health', 'AW-PURE-EYES', 0, '[]'::jsonb, null, null, 50.7, true),
  (194, '5-hour Extra', '5-hour', 'MERCHANDISE', 'Energy Shots', 'AW-5-HOUR-EXTRA', 7, '["Berry","blue raspberry","grape","mango peach","strawberry watermelon","strawberry banana","tidal twist"]'::jsonb, '5_hour_extra.jpg', null, 9.79, true),
  (195, '5-hour regular', '5-hour', 'MERCHANDISE', 'Energy Shots', 'AW-5-HOUR-REGULAR', 2, '["Berry","grape"]'::jsonb, null, null, 32.02, true),
  (196, 'Advil', 'Advil', 'MERCHANDISE', 'OTC & Health', 'AW-ADVIL', 6, '["Regular","Sinus","PM","dual action","liquid gels","allergy"]'::jsonb, null, null, 75.7, true),
  (197, 'Haribo Bags', 'Haribo', 'CANDIES', 'Bags', 'AW-HARIBO-BAGS', 7, '["Gold bears","gold bears tropical","gold bears sour","sour streamers","Smurfs","sour Smurfs","twin snakes"]'::jsonb, 'haribo_bags.webp', null, 11.79, true),
  (198, 'Trolli bags', 'Trolli', 'CANDIES', 'Bags', 'AW-TROLLI-BAGS', 3, '["Sour brite crawlers","peach","octopus"]'::jsonb, 'trolli_bags.webp', null, 42.92, true),
  (199, 'Gushers bags', 'Gushers', 'CANDIES', 'Bags', 'AW-GUSHERS-BAGS', 0, '[]'::jsonb, 'gushers_bags.jpg', null, 30.74, true),
  (200, 'Nerds bags', 'Nerds', 'CANDIES', 'Bags', 'AW-NERDS-BAGS', 4, '["Red","blue","yellow","cherry lemonade"]'::jsonb, 'nerds_pouches_1.webp', null, 22.15, true),
  (201, 'Lifesaver bags', 'Lifesaver', 'CANDIES', 'Bags', 'AW-LIFESAVER-BAGS', 7, '["5-flavors","collision","wildberry","sours","fruit rings","XO rings","exotics"]'::jsonb, 'lifesaver_bags.webp', null, 40.97, true),
  (202, 'Rips bags', 'Rips', 'CANDIES', 'Bags', 'AW-RIPS-BAGS', 1, '["Grape"]'::jsonb, 'rips_bags.webp', null, 31.7, true),
  (203, 'Welches bags', 'Welches', 'CANDIES', 'Bags', 'AW-WELCHES-BAGS', 0, '[]'::jsonb, 'welches_bags.webp', null, 26.75, true),
  (204, 'Welches', 'Welches', 'DRINKS & BAGS', 'Juices & Teas', 'AW-WELCHES', 7, '["Cranberry","fruit punch","apple","grape","orange pineapple","mango passion","orange"]'::jsonb, 'welches_juice.jpg', null, 14.47, true),
  (205, 'Pepsi', 'Pepsi', 'DRINKS & BAGS', 'Sodas', 'AW-PEPSI', 0, '[]'::jsonb, null, null, 14.17, true),
  (206, 'Dr Pepper', 'Dr Pepper', 'DRINKS & BAGS', 'Sodas', 'AW-DR-PEPPER', 0, '[]'::jsonb, null, null, 53.95, true),
  (207, '20oz Minute Maid', '20oz', 'DRINKS & BAGS', 'Juices & Teas', 'AW-20OZ-MINUTE-MA', 9, '["Blue","fruit punch","berry","lemonade","pink lemonade","watermelon","peach","kiwi strawberry"]'::jsonb, null, null, 32.89, true),
  (208, '12oz Minute Maid', '12oz', 'DRINKS & BAGS', 'Juices & Teas', 'AW-12OZ-MINUTE-MA', 6, '["Orange pineapple","orange","cranberry","raspberry","apple","tropical"]'::jsonb, '12oz_minute_maid_juice.webp', null, 17.4, true),
  (209, '24/7', '24/7', 'TOBACCO', 'Cigarettes', 'AW-24-7', 8, '["Menthol 100","menthol short","red 100","red short","silver 100","silver short","gold 100","gold short"]'::jsonb, '24_7.jpg', null, 83.28, true),
  (210, 'Seneca Filter', 'Seneca', 'TOBACCO', 'Cigarettes', 'AW-SENECA-FILTER', 0, '[]'::jsonb, 'seneca_filter_cigarettes.jpg', null, 76.71, true),
  (211, 'Cheyenne', 'Cheyenne', 'TOBACCO', 'Cigarettes', 'AW-CHEYENNE', 0, '[]'::jsonb, null, null, 26.71, true),
  (212, 'Ice bags', 'Ice bags', 'DRINKS & BAGS', 'Bags & Carriers', 'AW-ICE-BAGS', 2, '["8lbs","10lbs"]'::jsonb, null, null, 29.55, true),
  (213, 'Lil leaf wraps', 'Lil leaf', 'TOBACCO', 'Wraps & Leafs', 'AW-LIL-LEAF-WRAPS', 1, '["Original"]'::jsonb, null, null, 68.08, true),
  (214, 'Tropicana big', 'Tropicana', 'DRINKS & BAGS', 'Juices & Teas', 'AW-TROPICANA-BIG', 4, '["Orange","cranberry","apple","ruby red"]'::jsonb, null, null, 12.15, true),
  (215, 'Alcapone leafs', 'Alcapone', 'TOBACCO', 'Wraps & Leafs', 'AW-ALCAPONE-LEAFS', 3, '["Rum","original","cognac"]'::jsonb, 'alcapone_wraps.jpg', null, 75.5, true),
  (216, 'Grinders', 'Grinders', 'NOVELTIES', 'Smoke Accessories', 'AW-GRINDERS', 3, '["Big","medium","small"]'::jsonb, null, null, 47.27, true),
  (217, 'Detox champ', 'Detox', 'NOVELTIES', 'Detox', 'AW-DETOX-CHAMP', 6, '["Blueberry","fruit punch","lemon lime","açaí berry","kiwi strawberry","grape"]'::jsonb, 'detox_champ.jpg', null, 118.98, true),
  (218, 'Q carbo 16', 'Q carbo', 'NOVELTIES', 'Detox', 'AW-Q-CARBO-16', 4, '["Grape","red","strawberry mango","orange"]'::jsonb, null, 'BESTSELLER', 46.26, true),
  (219, 'Happy valentines jar', 'Happy', 'NOVELTIES', 'Wellness Pills', 'AW-HAPPY-VALENTIN', 3, '["4 inch","6 inch","colored"]'::jsonb, null, null, 95.75, true),
  (220, 'Scales', 'Scales', 'NOVELTIES', 'Smoke Accessories', 'AW-SCALES', 3, '["Big","medium","small"]'::jsonb, null, null, 54.34, true),
  (221, 'Cheap scales', 'Cheap', 'NOVELTIES', 'Smoke Accessories', 'AW-CHEAP-SCALES', 3, '["Bog","medium","small"]'::jsonb, null, null, 83.63, true),
  (222, 'Pepcid complete', 'Pepcid', 'MERCHANDISE', 'OTC & Health', 'AW-PEPCID-COMPLET', 0, '[]'::jsonb, null, null, 74.94, true),
  (223, 'Bayer', 'Bayer', 'MERCHANDISE', 'OTC & Health', 'AW-BAYER', 0, '[]'::jsonb, null, null, 69.39, true),
  (224, 'Mucinex DM', 'Mucinex', 'MERCHANDISE', 'OTC & Health', 'AW-MUCINEX-DM', 0, '[]'::jsonb, null, null, 20.15, true),
  (225, 'Women deodorant', 'Women', 'GROCERY', 'Personal Care', 'AW-WOMEN-DEODORAN', 0, '[]'::jsonb, 'women_s_deodorant.webp', null, 11.47, true),
  (226, 'Excedrin', 'Excedrin', 'MERCHANDISE', 'OTC & Health', 'AW-EXCEDRIN', 2, '["Extra","migraine"]'::jsonb, null, null, 55.25, true),
  (227, 'BC', 'BC', 'MERCHANDISE', 'OTC & Health', 'AW-BC', 3, '["6pk","2pk","arthritis"]'::jsonb, null, null, 42.87, true),
  (228, 'Stanback', 'Stanback', 'MERCHANDISE', 'OTC & Health', 'AW-STANBACK', 2, '["6pk","2pk"]'::jsonb, null, null, 65.1, true),
  (229, 'Tums small', 'Tums', 'MERCHANDISE', 'OTC & Health', 'AW-TUMS-SMALL', 3, '["Assorted fruit","berries","mint"]'::jsonb, null, null, 43.63, true),
  (230, 'Tums big', 'Tums', 'MERCHANDISE', 'OTC & Health', 'AW-TUMS-BIG', 3, '["Assorted fruit","berries","mint"]'::jsonb, null, null, 65.1, true),
  (231, 'Rolaids', 'Rolaids', 'MERCHANDISE', 'OTC & Health', 'AW-ROLAIDS', 2, '["Mint","fruit"]'::jsonb, null, null, 30.5, true),
  (232, 'Alani', 'Alani', 'DRINKS & BAGS', 'Energy Drinks', 'AW-ALANI', 3, '["Cherry slush","blue slush","sherbet"]'::jsonb, null, null, 27.55, true),
  (233, 'Nesquick', 'Nesquick', 'DRINKS & BAGS', 'Dairy & Milk', 'AW-NESQUICK', 4, '["Chocolate","strawberry","vanilla","strawberry banana"]'::jsonb, null, null, 51.69, true),
  (234, 'Foco', 'Foco', 'DRINKS & BAGS', 'Juices & Teas', 'AW-FOCO', 2, '["Big","small"]'::jsonb, null, null, 34.48, true),
  (235, 'Kuii nata', 'Kuii', 'DRINKS & BAGS', 'Juices & Teas', 'AW-KUII-NATA', 5, '["Melon","original","strawberry","mango","pineapple"]'::jsonb, null, null, 39.63, true),
  (236, 'OHM bags small', 'OHM bags', 'TOBACCO', 'Loose Tobacco Bags', 'AW-OHM-BAGS-SMALL', 4, '["Bold","menthol","blue","natural"]'::jsonb, null, null, 101.26, true),
  (237, 'OHM bags big', 'OHM bags', 'TOBACCO', 'Loose Tobacco Bags', 'AW-OHM-BAGS-BIG', 6, '["Bold","menthol","blue","natural","Turkish red","menthol gold"]'::jsonb, null, null, 31.71, true),
  (238, 'Gambler bags big', 'Gambler', 'TOBACCO', 'Loose Tobacco Bags', 'AW-GAMBLER-BAGS-B', 4, '["Red","gold","silver","menthol"]'::jsonb, null, null, 58.28, true),
  (239, 'Gambler bags small', 'Gambler', 'TOBACCO', 'Loose Tobacco Bags', 'AW-GAMBLER-BAGS-S', 4, '["Red","gold","silver","menthol"]'::jsonb, null, null, 53.28, true),
  (240, 'American club bags big', 'American', 'TOBACCO', 'Loose Tobacco Bags', 'AW-AMERICAN-CLUB-', 3, '["Menthol","red","blue"]'::jsonb, 'american_club.png', null, 68.03, true),
  (241, 'American club bags small', 'American', 'TOBACCO', 'Loose Tobacco Bags', 'AW-AMERICAN-CLUB-', 3, '["Menthol","red","blue"]'::jsonb, 'american_club.png', null, 31.26, true),
  (242, 'Gambler tubes', 'Gambler', 'TOBACCO', 'Tubes & Filters', 'AW-GAMBLER-TUBES', 6, '["Gold 100","gold king","menthol 100","menthol king","red 100","red king"]'::jsonb, 'gambler_tubes.webp', null, 17.07, true),
  (243, 'Tube cuts', 'Tube', 'TOBACCO', 'Tubes & Filters', 'AW-TUBE-CUTS', 8, '["Gold 100","gold king","menthol 100","menthol king","orange 100","orange king","silver 100","silver king"]'::jsonb, 'tube_cuts.webp', null, 61.91, true),
  (244, 'Shargio tubes', 'Shargio', 'TOBACCO', 'Tubes & Filters', 'AW-SHARGIO-TUBES', 6, '["Green 250","green 200","blue 250","blue 200","red 250","red 200"]'::jsonb, 'shargio_tubes.jpg', null, 39.19, true),
  (245, 'Blunteffect incense', 'Blunteffect', 'MERCHANDISE', 'Air Fresheners & Incense', 'AW-BLUNTEFFECT-IN', 3, '["Small","medium","big"]'::jsonb, 'blunteffect_incense_medium.webp', null, 31.76, true),
  (246, 'Cheap incense', 'Cheap', 'MERCHANDISE', 'Air Fresheners & Incense', 'AW-CHEAP-INCENSE', 3, '["Small","medium","big"]'::jsonb, null, null, 53.98, true),
  (247, 'Lattafa air freshener', 'Lattafa', 'MERCHANDISE', 'Air Fresheners & Incense', 'AW-LATTAFA-AIR-FR', 1, '["Pink"]'::jsonb, 'lattafa_air_freshener.webp', null, 78.98, true),
  (248, 'Coke', 'Coke', 'DRINKS & BAGS', 'Sodas', 'AW-COKE', 0, '[]'::jsonb, null, null, 28.94, true),
  (249, 'Sprite', 'Sprite', 'DRINKS & BAGS', 'Sodas', 'AW-SPRITE', 2, '["Regular","tropical"]'::jsonb, null, null, 14.33, true),
  (250, 'Cheap lighters', 'Cheap', 'MERCHANDISE', 'Lighters & Torches', 'AW-CHEAP-LIGHTERS', 0, '[]'::jsonb, 'cheap_lighters.jpg', null, 31.01, true),
  (251, 'Supreme', 'Supreme', 'TOBACCO', 'Cigars & Cigarillos', 'AW-SUPREME', 2, '["Green","haze"]'::jsonb, 'supreme.jpg', null, 109.29, true),
  (252, 'Playing cards', 'Playing', 'MERCHANDISE', 'Counter Goods', 'AW-PLAYING-CARDS', 2, '["Aviator","cheap"]'::jsonb, null, null, 71.66, true),
  (253, 'Ajax detergent', 'Ajax', 'GROCERY', 'Cleaning', 'AW-AJAX-DETERGENT', 0, '[]'::jsonb, null, null, 34.46, true),
  (254, 'Luffbar', 'Luffbar', 'NOVELTIES', 'Disposable Vapes', 'AW-LUFFBAR', 1, '["Alaska"]'::jsonb, null, null, 96.76, true),
  (255, 'Raw papers', 'Raw papers', 'TOBACCO', 'Papers & Cones', 'AW-RAW-PAPERS', 2, '["Classic 1 1/4","classic king size slim"]'::jsonb, 'raw_papers.jpg', null, 98.18, true),
  (256, 'Raw cones', 'Raw cones', 'TOBACCO', 'Papers & Cones', 'AW-RAW-CONES', 6, '["Classic 6X","classic 3X","organic 6X","organic 3X","black 6X","black 3X"]'::jsonb, 'raw_cones.jpg', null, 55.9, true),
  (257, 'Top Paper', 'Top Paper', 'TOBACCO', 'Papers & Cones', 'AW-TOP-PAPER', 2, '["Jar","box"]'::jsonb, 'top_paper.jpg', null, 43.43, true),
  (258, 'Psyched pre rolls jars', 'Psyched', 'NOVELTIES', 'Mushroom Products', 'AW-PSYCHED-PRE-RO', 1, '["Any flavor"]'::jsonb, null, null, 40.2, true),
  (259, 'Paper plates', 'Paper', 'GROCERY', 'Paper & Plastic', 'AW-PAPER-PLATES', 2, '["Big","small"]'::jsonb, null, null, 27.55, true),
  (260, 'Backwoods true wraps', 'Backwoods', 'TOBACCO', 'Wraps & Leafs', 'AW-BACKWOODS-TRUE', 3, '["Original","vanilla","aromatic"]'::jsonb, null, null, 42.97, true),
  (261, 'Lighter leash', 'Lighter', 'MERCHANDISE', 'Lighters & Torches', 'AW-LIGHTER-LEASH', 3, '["Regular","with clip","with design"]'::jsonb, null, null, 70.15, true),
  (262, 'Efrutti jar', 'Efrutti', 'CANDIES', 'Jars', 'AW-EFRUTTI-JAR', 1, '["Blue"]'::jsonb, 'efrutti_jar.webp', null, 35.86, true),
  (263, 'WO mini', 'WO mini', 'TOBACCO', 'Cigars & Cigarillos', 'AW-WO-MINI', 4, '["Silver","red sweet","white grape","blue raspberry"]'::jsonb, 'wo_mini.png', null, 83.93, true),
  (264, 'NyQuil', 'NyQuil', 'MERCHANDISE', 'OTC & Health', 'AW-NYQUIL', 0, '[]'::jsonb, null, null, 33.78, true),
  (265, 'Hard steel', 'Hard', 'MERCHANDISE', 'Honey & Energy', 'AW-HARD-STEEL', 6, '["Shots","honey","pills","gold shots","gold honey","gold pills"]'::jsonb, 'hard_steel_honey.avif', 'PREMIUM', 24.19, true),
  (266, 'Blue wolf honey', 'Blue', 'MERCHANDISE', 'Honey & Energy', 'AW-BLUE-WOLF-HONE', 0, '[]'::jsonb, null, null, 38.33, true),
  (267, 'ZYN European', 'ZYN European', 'TOBACCO', 'Pouches & ZYN', 'AW-ZYN-EUROPEAN', 1, '["Mix"]'::jsonb, 'zyn_6mg.webp', null, 50.4, true),
  (268, 'Sour strips', 'Sour', 'CANDIES', 'Sweets & Gummies', 'AW-SOUR-STRIPS', 1, '["Blue"]'::jsonb, null, null, 26.76, true),
  (269, 'Airheads soda', 'Airheads', 'DRINKS & BAGS', 'Sodas', 'AW-AIRHEADS-SODA', 5, '["Green","red","blue","pink","orange"]'::jsonb, null, null, 20.73, true),
  (270, 'Monster', 'Monster', 'DRINKS & BAGS', 'Energy Drinks', 'AW-MONSTER', 3, '["Green","white","blue"]'::jsonb, null, 'DEAL', 47.62, true),
  (271, 'Snickers chocolate milk', 'Snickers', 'DRINKS & BAGS', 'Dairy & Milk', 'AW-SNICKERS-CHOCO', 0, '[]'::jsonb, null, null, 45.52, true),
  (272, 'Jumex', 'Jumex', 'DRINKS & BAGS', 'Juices & Teas', 'AW-JUMEX', 5, '["Mango","guava","strawberries banana","peach","pineapple cocount"]'::jsonb, null, null, 22.08, true),
  (273, 'Loose leafs splits diamond wraps', 'Loose', 'TOBACCO', 'Wraps & Leafs', 'AW-LOOSE-LEAFS-SP', 0, '[]'::jsonb, 'loose_leafs_wraps_5pk.webp', null, 84.09, true),
  (274, 'Raw guarana wraps', 'Raw guarana', 'TOBACCO', 'Wraps & Leafs', 'AW-RAW-GUARANA-WR', 0, '[]'::jsonb, null, null, 42.87, true),
  (275, 'Jolly rancher 5lbs', 'Jolly', 'CANDIES', 'Sweets & Gummies', 'AW-JOLLY-RANCHER-', 0, '[]'::jsonb, 'jolly_rancher_5lbs.webp', null, 35.59, true),
  (276, 'Now and later jar', 'Now and', 'CANDIES', 'Jars', 'AW-NOW-AND-LATER-', 0, '[]'::jsonb, 'now_later_jar.webp', null, 41.8, true),
  (277, 'Jungle jollies', 'Jungle', 'CANDIES', 'Sweets & Gummies', 'AW-JUNGLE-JOLLIES', 0, '[]'::jsonb, 'jungle_jollies.jpg', null, 36.33, true),
  (278, 'Van holt', 'Van holt', 'FOOD STUFF', 'Quick Meals', 'AW-VAN-HOLT', 5, '["Big papa","hot mama","garlic Joe","kosher","dill"]'::jsonb, 'van_holt_pickles.jpg', null, 27.97, true),
  (279, 'Yakisoba', 'Yakisoba', 'FOOD STUFF', 'Quick Meals', 'AW-YAKISOBA', 2, '["Beef","chicken"]'::jsonb, 'yakisoba_noodles.jpg', null, 19.49, true),
  (280, 'Coastal', 'Coastal', 'MOTOR OIL', 'Motor Oil', 'AW-COASTAL', 2, '["5w30","5w20"]'::jsonb, 'coastal_moto_oil.jpg', null, 44.56, true),
  (281, 'Hush hit pre rolls 2pk', 'Hush', 'NOVELTIES', 'Mushroom Products', 'AW-HUSH-HIT-PRE-R', 1, '["Blue dream"]'::jsonb, null, null, 116.96, true),
  (282, 'JOB papers', 'JOB papers', 'TOBACCO', 'Papers & Cones', 'AW-JOB-PAPERS', 4, '["1.5","1.25","1.0","1.5 slim"]'::jsonb, 'job_papers.jpg', 'BESTSELLER', 93.83, true),
  (283, 'Duct tape', 'Duct', 'GROCERY', 'Hardware', 'AW-DUCT-TAPE', 0, '[]'::jsonb, null, null, 14.02, true),
  (284, 'Clear tape', 'Clear', 'GROCERY', 'Hardware', 'AW-CLEAR-TAPE', 0, '[]'::jsonb, null, null, 26.78, true),
  (285, 'Shroom bang pre rolls 2pk', 'Shroom', 'NOVELTIES', 'Mushroom Products', 'AW-SHROOM-BANG-PR', 2, '["Purple","blue"]'::jsonb, null, null, 36.16, true),
  (286, 'AA cellular Bluetooth headphones', 'AA cellular', 'MERCHANDISE', 'Electronics', 'AW-AA-CELLULAR-BL', 0, '[]'::jsonb, null, null, 12.57, true),
  (287, 'Eagle torches', 'Eagle', 'MERCHANDISE', 'Lighters & Torches', 'AW-EAGLE-TORCHES', 3, '["Big","medium","small"]'::jsonb, 'eagles_torches_3.jpg', null, 66.86, true),
  (288, 'Blue monkey pre rolls 2pk', 'Blue', 'NOVELTIES', 'Mushroom Products', 'AW-BLUE-MONKEY-PR', 2, '["Space monkey","blue razz"]'::jsonb, null, null, 38.18, true),
  (289, 'Psyched disposable 9000mg', 'Psyched', 'NOVELTIES', 'Mushroom Products', 'AW-PSYCHED-DISPOS', 1, '["Snow lotus"]'::jsonb, null, null, 82.62, true),
  (290, 'Powerade big', 'Powerade', 'DRINKS & BAGS', 'Sports Drinks', 'AW-POWERADE-BIG', 4, '["Blue","red","grape","yellow"]'::jsonb, 'powerade_20oz.webp', null, 48.65, true),
  (291, 'Powerade small', 'Powerade', 'DRINKS & BAGS', 'Sports Drinks', 'AW-POWERADE-SMALL', 4, '["Blue","red","grape","yellow"]'::jsonb, 'powerade_20oz.webp', null, 19.97, true),
  (292, 'Electrolyte', 'Electrolyte', 'DRINKS & BAGS', 'Energy Drinks', 'AW-ELECTROLYTE', 1, '["Blue"]'::jsonb, 'electrolyte.webp', null, 46.31, true),
  (293, 'Sip happens', 'Sip happens', 'NOVELTIES', 'Kratom & Kava', 'AW-SIP-HAPPENS', 0, '[]'::jsonb, null, null, 118.98, true),
  (294, 'PIK 16mg', 'PIK 16mg', 'TOBACCO', 'Pouches & ZYN', 'AW-PIK-16MG', 1, '["Wintergreen"]'::jsonb, 'pik_16mg.jpg', null, 81.76, true),
  (295, 'Snack wraps', 'Snack', 'FOOD STUFF', 'Chips & Crackers', 'AW-SNACK-WRAPS', 2, '["40ct","12ct"]'::jsonb, null, null, 45.95, true),
  (296, 'Jelly holes pre rolls', 'Jelly', 'NOVELTIES', 'Mushroom Products', 'AW-JELLY-HOLES-PR', 1, '["Dirty girl"]'::jsonb, null, null, 112.92, true),
  (297, 'Toothbrushes', 'Toothbrushes', 'GROCERY', 'Personal Care', 'AW-TOOTHBRUSHES', 0, '[]'::jsonb, null, null, 27.79, true),
  (298, 'Shroom rolls pre rolls jars', 'Shroom', 'NOVELTIES', 'Mushroom Products', 'AW-SHROOM-ROLLS-P', 0, '[]'::jsonb, null, null, 49.29, true),
  (299, 'Psyched 6000mg disposable', 'Psyched', 'NOVELTIES', 'Mushroom Products', 'AW-PSYCHED-6000MG', 1, '["Snow lotus"]'::jsonb, null, null, 43.23, true),
  (300, 'Melted mushroom pre rolls 2pk', 'Melted', 'NOVELTIES', 'Mushroom Products', 'AW-MELTED-MUSHROO', 1, '["Blue razz"]'::jsonb, null, null, 110.9, true),
  (301, 'Xuno pills', 'Xuno', 'NOVELTIES', 'Wellness Pills', 'AW-XUNO-PILLS', 0, '[]'::jsonb, null, null, 54.34, true),
  (302, 'Better me pills', 'Better', 'NOVELTIES', 'Wellness Pills', 'AW-BETTER-ME-PILL', 0, '[]'::jsonb, null, null, 119.99, true),
  (303, 'High gravity pills', 'High', 'NOVELTIES', 'Wellness Pills', 'AW-HIGH-GRAVITY-P', 0, '[]'::jsonb, null, null, 80.6, true),
  (304, 'Third eye pills', 'Third', 'NOVELTIES', 'Wellness Pills', 'AW-THIRD-EYE-PILL', 0, '[]'::jsonb, null, null, 99.79, true),
  (305, 'Tyson wraps', 'Tyson', 'TOBACCO', 'Wraps & Leafs', 'AW-TYSON-WRAPS', 0, '[]'::jsonb, 'tyson_wraps.jpg', null, 102.07, true),
  (306, 'Stoned mushroom gummies bags regular', 'Stoned', 'NOVELTIES', 'Mushroom Products', 'AW-STONED-MUSHROO', 0, '[]'::jsonb, null, null, 89.69, true),
  (307, 'Stoned honey mushroom bags', 'Stoned', 'NOVELTIES', 'Mushroom Products', 'AW-STONED-HONEY-M', 0, '[]'::jsonb, null, null, 113.93, true),
  (308, 'Upass', 'Upass', 'NOVELTIES', 'Detox', 'AW-UPASS', 0, '[]'::jsonb, 'upass.webp', null, 114.94, true),
  (309, 'Water bongs', 'Water', 'NOVELTIES', 'Smoke Accessories', 'AW-WATER-BONGS', 0, '[]'::jsonb, null, null, 112.92, true),
  (310, 'Geekbar mate', 'Geekbar', 'NOVELTIES', 'Disposable Vapes', 'AW-GEEKBAR-MATE', 0, '[]'::jsonb, 'geekbar_15k.webp', null, 94.74, true),
  (311, 'Geekbar mate pods', 'Geekbar', 'NOVELTIES', 'Vape Pods', 'AW-GEEKBAR-MATE-P', 0, '[]'::jsonb, null, null, 112.92, true),
  (312, 'Stoned blue lotus gummies bags', 'Stoned', 'NOVELTIES', 'Mushroom Products', 'AW-STONED-BLUE-LO', 0, '[]'::jsonb, null, null, 106.86, true),
  (313, 'Psyched blue lotus gummies 25ct box', 'Psyched', 'NOVELTIES', 'Mushroom Products', 'AW-PSYCHED-BLUE-L', 0, '[]'::jsonb, null, null, 22.02, true),
  (314, 'Coco Nara charcoal', 'Coco', 'NOVELTIES', 'Hookah & Shisha', 'AW-COCO-NARA-CHAR', 4, '["Big","small","medium","1kg"]'::jsonb, null, null, 95.75, true),
  (315, 'Alfakher 50 gram', 'Alfakher', 'NOVELTIES', 'Hookah & Shisha', 'AW-ALFAKHER-50-GR', 1, '["Mint"]'::jsonb, 'alfakher_50_gram.webp', null, 70.5, true),
  (316, 'Alfakher 250 gram', 'Alfakher', 'NOVELTIES', 'Hookah & Shisha', 'AW-ALFAKHER-250-G', 1, '["Mint"]'::jsonb, 'alfakher_250_gram.webp', null, 71.51, true),
  (317, 'Alfakher 1KG', 'Alfakher', 'NOVELTIES', 'Hookah & Shisha', 'AW-ALFAKHER-1KG', 1, '["Mint"]'::jsonb, 'alfakher_250_gram.webp', null, 49.29, true),
  (318, 'Tyson papers', 'Tyson', 'TOBACCO', 'Papers & Cones', 'AW-TYSON-PAPERS', 2, '["Yellow","regular"]'::jsonb, 'tyson_wraps.jpg', null, 40.5, true),
  (319, 'Wild hemp', 'Wild', 'TOBACCO', 'Wraps & Leafs', 'AW-WILD-HEMP', 1, '["Natural"]'::jsonb, 'wild_hemps.jpg', null, 15.1, true),
  (320, 'King palm', 'King', 'TOBACCO', 'Wraps & Leafs', 'AW-KING-PALM', 1, '["Regular"]'::jsonb, 'king_palm.jpg', null, 81.16, true),
  (321, 'VIP gold honey', 'VIP gold', 'MERCHANDISE', 'Honey & Energy', 'AW-VIP-GOLD-HONEY', 0, '[]'::jsonb, 'vip_gold_honey.webp', 'PREMIUM', 29.49, true),
  (322, 'Secret miracle honey', 'Secret', 'MERCHANDISE', 'Honey & Energy', 'AW-SECRET-MIRACLE', 0, '[]'::jsonb, 'secret_miracle_honey_1.jpg', null, 37.82, true),
  (323, 'Beer salts bottles', 'Beer', 'FOOD STUFF', 'Sauces & Salts', 'AW-BEER-SALTS-BOT', 2, '["Lemon lime","lime"]'::jsonb, 'twang_beer_salts_bottles.jpg', null, 46.96, true),
  (324, 'Beer salts packets', 'Beer', 'FOOD STUFF', 'Sauces & Salts', 'AW-BEER-SALTS-PAC', 2, '["Yellow","green"]'::jsonb, 'twang_beer_salts_packets.webp', null, 37.67, true),
  (325, 'Jarritos', 'Jarritos', 'DRINKS & BAGS', 'Juices & Teas', 'AW-JARRITOS', 1, '["Orange"]'::jsonb, 'jarritos.jpg', null, 14.13, true),
  (326, 'Maruchan cups', 'Maruchan', 'FOOD STUFF', 'Quick Meals', 'AW-MARUCHAN-CUPS', 3, '["Chicken","beef","shrimp"]'::jsonb, 'maruchan_packs.jpg', null, 40.9, true),
  (327, 'Maruchan packs', 'Maruchan', 'FOOD STUFF', 'Quick Meals', 'AW-MARUCHAN-PACKS', 3, '["Chicken","beef","shrimp"]'::jsonb, 'maruchan_packs.jpg', null, 25.35, true),
  (328, 'Takis', 'Takis', 'FOOD STUFF', 'Chips & Crackers', 'AW-TAKIS', 4, '["Fuego small","fuego big","blue heat small","blue heat big"]'::jsonb, 'takis.webp', 'BESTSELLER', 17.07, true),
  (329, 'Raw', 'Raw', 'TOBACCO', 'Cigars & Cigarillos', 'AW-RAW', 1, '["Tips"]'::jsonb, 'raw_papers.jpg', null, 26.86, true),
  (330, 'High hemp', 'High', 'TOBACCO', 'Wraps & Leafs', 'AW-HIGH-HEMP', 1, '["Organic"]'::jsonb, 'high_hemp_organic.webp', null, 79.64, true),
  (331, 'Panasonic', 'Panasonic', 'MERCHANDISE', 'Electronics', 'AW-PANASONIC', 1, '["AAA2"]'::jsonb, null, null, 51.96, true),
  (332, 'Black tiger honey', 'Black', 'MERCHANDISE', 'Honey & Energy', 'AW-BLACK-TIGER-HO', 2, '["Flat box","round box"]'::jsonb, 'black_tiger_honey.jpg', 'PREMIUM', 8.28, true),
  (333, 'Gain dishwasher', 'Gain', 'GROCERY', 'Laundry & Detergent', 'AW-GAIN-DISHWASHE', 0, '[]'::jsonb, 'gain.jpg', null, 7.83, true),
  (334, 'Bandaids', 'Bandaids', 'MERCHANDISE', 'OTC & Health', 'AW-BANDAIDS', 0, '[]'::jsonb, null, null, 29.74, true),
  (335, 'Gatorade small', 'Gatorade', 'DRINKS & BAGS', 'Sports Drinks', 'AW-GATORADE-SMALL', 1, '["Blue"]'::jsonb, null, null, 51.72, true),
  (336, 'Gatorade big', 'Gatorade', 'DRINKS & BAGS', 'Sports Drinks', 'AW-GATORADE-BIG', 1, '["Blue"]'::jsonb, null, 'BESTSELLER', 28.62, true),
  (337, 'Bob Marley papers', 'Bob Marley', 'TOBACCO', 'Papers & Cones', 'AW-BOB-MARLEY-PAP', 9, '["Yellow small","yellow big","yellow big with tips","organic small","organic big","organic big with tips","silver small","silver big"]'::jsonb, 'bob_marley_papers.jpg', null, 41.11, true),
  (338, 'Grabba leaf', 'Grabba', 'TOBACCO', 'Wraps & Leafs', 'AW-GRABBA-LEAF', 4, '["Big","small","small yellow","big yellow"]'::jsonb, 'grabba_leaf_small.webp', null, 50.9, true),
  (339, 'Billionaire wraps', 'Billionaire', 'TOBACCO', 'Wraps & Leafs', 'AW-BILLIONAIRE-WR', 1, '["Russian cream"]'::jsonb, 'billionaire_wraps.jpg', null, 49.09, true),
  (340, 'Slapwoods singles', 'Slapwoods', 'TOBACCO', 'Cigars & Cigarillos', 'AW-SLAPWOODS-SING', 1, '["Russian cream"]'::jsonb, 'slapwoods_5pk.webp', null, 92.77, true),
  (341, 'Silly dots pills', 'Silly', 'NOVELTIES', 'Wellness Pills', 'AW-SILLY-DOTS-PIL', 1, '["Cherry"]'::jsonb, null, null, 48.28, true),
  (342, 'Dubai chocolate', 'Dubai', 'CANDIES', 'Chocolate Bars', 'AW-DUBAI-CHOCOLAT', 2, '["Small","big"]'::jsonb, null, 'NEW', 31.01, true),
  (343, 'Gummy', 'Gummy', 'CANDIES', 'Gum & Mints', 'AW-GUMMY', 6, '["Burger","pizza","hotdog","cupcake","SpongeBob","sour burger"]'::jsonb, 'efrutti_gummy.webp', null, 18.5, true),
  (344, 'Krazy glue', 'Krazy', 'GROCERY', 'Hardware', 'AW-KRAZY-GLUE', 0, '[]'::jsonb, 'krazy_glue.jpg', null, 18.34, true),
  (345, 'Super glue', 'Super', 'GROCERY', 'Hardware', 'AW-SUPER-GLUE', 0, '[]'::jsonb, null, null, 26.38, true),
  (346, 'Monster Java', 'Monster', 'DRINKS & BAGS', 'Energy Drinks', 'AW-MONSTER-JAVA', 0, '[]'::jsonb, null, null, 26.05, true),
  (347, 'Zigzag hemp wraps', 'Zigzag', 'TOBACCO', 'Wraps & Leafs', 'AW-ZIGZAG-HEMP-WR', 1, '["Natural"]'::jsonb, 'zigzag_hemp_wraps.jpg', null, 39.69, true),
  (348, 'Oreo', 'Oreo', 'FOOD STUFF', 'Cookies', 'AW-OREO', 1, '["Regular"]'::jsonb, 'oreo_cookies_single.jpg', 'BESTSELLER', 49.19, true),
  (349, 'Nutter butter', 'Nutter', 'FOOD STUFF', 'Cookies', 'AW-NUTTER-BUTTER', 1, '["Regular"]'::jsonb, null, null, 44.74, true),
  (350, 'Uncle Al’s', 'Uncle', 'FOOD STUFF', 'Cookies', 'AW-UNCLE-AL-S', 0, '[]'::jsonb, 'uncle_al_s_cookies.jpg', null, 33.23, true),
  (351, 'Uncle Al’s cookies', 'Uncle', 'FOOD STUFF', 'Cookies', 'AW-UNCLE-AL-S-COO', 1, '["Lemon ice"]'::jsonb, 'uncle_al_s_cookies.jpg', null, 18.68, true),
  (352, 'Louisiana Hot sauce', 'Louisiana', 'FOOD STUFF', 'Sauces & Salts', 'AW-LOUISIANA-HOT-', 0, '[]'::jsonb, 'louisiana_hot_sauce.jpg', null, 48.98, true),
  (353, 'Instant coffee', 'Instant', 'FOOD STUFF', 'Coffee', 'AW-INSTANT-COFFEE', 2, '["Small","big"]'::jsonb, null, null, 11.61, true),
  (354, 'Folgers coffee', 'Folgers', 'FOOD STUFF', 'Coffee', 'AW-FOLGERS-COFFEE', 1, '["Small"]'::jsonb, null, null, 39.69, true),
  (355, 'Gold band', 'Gold', 'MOTOR OIL', 'Motor Oil', 'AW-GOLD-BAND', 1, '["Type A"]'::jsonb, 'gold_band.jpg', null, 48.28, true),
  (356, 'Gas cans', 'Gas cans', 'MOTOR OIL', 'Auto Accessories', 'AW-GAS-CANS', 3, '["1 gal","2gal","5 gal"]'::jsonb, null, null, 30.1, true),
  (357, 'Starbust bars', 'Starbust', 'CANDIES', 'Sweets & Gummies', 'AW-STARBUST-BARS', 1, '["Fave reds share size"]'::jsonb, null, null, 14.91, true),
  (358, 'Lifesaver share size gummies', 'Lifesaver', 'CANDIES', 'Gum & Mints', 'AW-LIFESAVER-SHAR', 1, '["Wildberry"]'::jsonb, 'lifesaver_gummies_share_size.webp', null, 41.05, true),
  (359, 'Cooking oil', 'Cooking', 'FOOD STUFF', 'Cooking Basics', 'AW-COOKING-OIL', 2, '["Small","big"]'::jsonb, 'cooking_oil.webp', null, 43.33, true),
  (360, 'Bug juice', 'Bug juice', 'DRINKS & BAGS', 'Juices & Teas', 'AW-BUG-JUICE', 1, '["Blue"]'::jsonb, null, null, 38.82, true),
  (361, 'Dominoes sugar', 'Dominoes', 'FOOD STUFF', 'Cooking Basics', 'AW-DOMINOES-SUGAR', 2, '["Small","big"]'::jsonb, null, null, 37.07, true),
  (362, 'Disposable gloved', 'Disposable', 'GROCERY', 'Hardware', 'AW-DISPOSABLE-GLO', 2, '["M size","L size"]'::jsonb, null, null, 18.14, true),
  (363, 'Durags', 'Durags', 'MERCHANDISE', 'Apparel', 'AW-DURAGS', 2, '["Black","white"]'::jsonb, null, null, 61.31, true),
  (364, 'Wave caps', 'Wave', 'MERCHANDISE', 'Apparel', 'AW-WAVE-CAPS', 2, '["Black","white"]'::jsonb, null, null, 68.13, true),
  (365, 'Orajel', 'Orajel', 'MERCHANDISE', 'OTC & Health', 'AW-ORAJEL', 0, '[]'::jsonb, null, null, 59.29, true),
  (366, 'Garcia Vega', 'Garcia', 'TOBACCO', 'Cigars & Cigarillos', 'AW-GARCIA-VEGA', 1, '["Green"]'::jsonb, null, null, 47.57, true),
  (367, 'Loose leafs 5pk', 'Loose', 'TOBACCO', 'Wraps & Leafs', 'AW-LOOSE-LEAFS-5P', 1, '["Watermelon"]'::jsonb, 'loose_leafs_wraps_5pk.webp', null, 109.49, true),
  (368, 'Camo wraps', 'Camo', 'TOBACCO', 'Wraps & Leafs', 'AW-CAMO-WRAPS', 1, '["Natural"]'::jsonb, null, null, 90.55, true)
on conflict (id) do update set
  name = excluded.name,
  brand = excluded.brand,
  cat = excluded.cat,
  sub = excluded.sub,
  sku = excluded.sku,
  flavors = excluded.flavors,
  variants = excluded.variants,
  img = excluded.img,
  tag = excluded.tag,
  price = excluded.price;
