-- The home page's hero photos, edited in Admin -> Homepage (AW-119, step 5).
--
-- The photos beside the home page's headline (src/components/HeroCarousel.jsx)
-- were constants in the code (HERO_SLIDES in src/data/content.js), so changing
-- them needed a deploy. This file moves them to a table that staff edit in
-- Admin -> Homepage (src/pages/admin/HomepageSection.jsx): add, describe,
-- link, reorder, turn off and delete photos. The homepage rails (New arrivals,
-- Bestsellers) are not stored here: they follow the products' tags and
-- homepage rank (20261010120000, src/lib/merchandising.js).
--
-- public.home_slides, one row per photo:
--   img               a photo bundled with the site (hero_candy.jpg, …) or
--                     the public address of a photo uploaded to the
--                     product-images bucket
--                     (https://<project>.supabase.co/storage/v1/object/public/product-images/…).
--                     Nothing else: the site's Content-Security-Policy
--                     (netlify.toml) loads images only from the site and
--                     https://*.supabase.co, the same rule as the product
--                     editor's PHOTO_URL (src/pages/admin/productForm.js).
--   alt               what the photo shows, for people who can't see it
--                     (1 to 200 characters)
--   go_cat            the department the slide links to; null: no link
--   nicotine_warning  the photo shows a nicotine product, so the FDA warning
--                     shows under it
--   sort              the order, 0 to 999, smallest first (ties by id)
--   active            shown on the home page; an inactive photo is kept for
--                     later. With every photo off the headline stands alone.
--   created_at, updated_at, updated_by (the admin who last changed the row)
--
-- Who may do what (row-level security):
--   - guests and signed-in accounts read the active rows;
--   - approved admins (is_admin()) read every row, and add, change and delete
--     rows;
--   - nobody else writes. The id comes from the identity column, which needs
--     no sequence privilege, so the sequence is granted to nobody but the
--     service role.
-- Uploads go to the product-images bucket (20261010120000) at
-- home/<upload time>-<name>.<ext>; its policies already let approved admins
-- write any path there, so storage is unchanged. A replaced or deleted photo
-- stays in the bucket, as for products.
--
-- The four photos the site shows today are added in today's order, only when
-- the table is empty, so the home page looks the same after this file and
-- running it again changes nothing. (On a table staff have emptied on
-- purpose, a re-run adds the four back: turn photos off rather than deleting
-- every one.)
--
-- Release: any time, before or after the frontend. The storefront falls back
-- to the photos bundled with it while the table is missing (PGRST205 or
-- 42P01) or can't be read, and Admin -> Homepage says that editing the
-- photos needs this update. The frontend deployed before it doesn't read the
-- table.

-- ---------------------------------------------------------------------------
-- The table.
-- ---------------------------------------------------------------------------
create table if not exists public.home_slides (
  id bigint generated by default as identity primary key,
  img text not null,
  alt text not null,
  go_cat text,
  nicotine_warning boolean not null default false,
  sort integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid(),
  constraint home_slides_img_chk check (
    img ~ '^hero_[a-z0-9_]+\.(jpg|jpeg|png|webp)$'
    or img ~ '^https://[a-z0-9-]+\.supabase\.co/storage/v1/object/public/product-images/'
  ),
  constraint home_slides_alt_chk check (char_length(alt) between 1 and 200),
  constraint home_slides_go_cat_chk check (char_length(go_cat) <= 60),
  constraint home_slides_sort_chk check (sort between 0 and 999)
);

create index if not exists home_slides_order_idx on public.home_slides (sort, id);

-- updated_at on every change (the initial schema's helper).
drop trigger if exists touch_home_slides on public.home_slides;
create trigger touch_home_slides before update on public.home_slides
  for each row execute function public.touch_updated_at();

-- updated_by is the admin who made the change (through the API; a change in
-- the SQL editor, which has no auth.uid(), leaves it as it was).
create or replace function public.stamp_home_slide_editor()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if auth.uid() is not null then
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

-- A trigger function: nobody calls it directly.
revoke all on function public.stamp_home_slide_editor() from public, anon, authenticated;

drop trigger if exists stamp_home_slide_editor on public.home_slides;
create trigger stamp_home_slide_editor before insert or update on public.home_slides
  for each row execute function public.stamp_home_slide_editor();

-- ---------------------------------------------------------------------------
-- Row-level security and privileges.
-- ---------------------------------------------------------------------------
alter table public.home_slides enable row level security;

drop policy if exists home_slides_public_read on public.home_slides;
create policy home_slides_public_read on public.home_slides
  for select to anon, authenticated
  using (active);

drop policy if exists home_slides_admin_read on public.home_slides;
create policy home_slides_admin_read on public.home_slides
  for select to authenticated
  using (public.is_admin());

drop policy if exists home_slides_admin_insert on public.home_slides;
create policy home_slides_admin_insert on public.home_slides
  for insert to authenticated
  with check (public.is_admin());

drop policy if exists home_slides_admin_update on public.home_slides;
create policy home_slides_admin_update on public.home_slides
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists home_slides_admin_delete on public.home_slides;
create policy home_slides_admin_delete on public.home_slides
  for delete to authenticated
  using (public.is_admin());

-- Supabase's default privileges give anon and authenticated everything on a
-- new table and sequence: revoke them, then grant what the policies need.
revoke all on public.home_slides from public, anon, authenticated;
grant select on public.home_slides to anon, authenticated;
grant insert, update, delete on public.home_slides to authenticated;
grant all on public.home_slides to service_role;
revoke all on sequence public.home_slides_id_seq from public, anon, authenticated;
grant usage, select on sequence public.home_slides_id_seq to service_role;

-- ---------------------------------------------------------------------------
-- Today's four photos (HERO_SLIDES), when the table is empty.
-- ---------------------------------------------------------------------------
insert into public.home_slides (img, alt, go_cat, nicotine_warning, sort)
select v.img, v.alt, v.go_cat, v.nicotine_warning, v.sort
from (values
  ('hero_candy.jpg', 'Display box of Turtles Bites chocolates', 'CANDIES', false, 10),
  ('hero_vape.jpg', 'Geek Bar Pulse X disposable vape advertisement', 'NOVELTIES', true, 20),
  ('hero_lighters.jpg', 'BIC lighters in a counter display tray', 'MERCHANDISE', false, 30),
  ('hero_gatorade.jpg', 'Gatorade and G2 bottles', 'DRINKS & BAGS', false, 40)
) as v (img, alt, go_cat, nicotine_warning, sort)
where not exists (select 1 from public.home_slides);

-- ---------------------------------------------------------------------------
-- Reverse (AW-213). Not run; copy into the SQL editor to undo this migration.
-- The frontend works without it: the home page shows the photos bundled with
-- it, and Admin -> Homepage says editing them needs the update. Photos
-- uploaded for slides stay in the product-images bucket until you delete
-- them in the dashboard.
--
-- drop table if exists public.home_slides;
-- drop function if exists public.stamp_home_slide_editor();
