-- Catalog corrections (AW-135, AW-138, AW-126; AW-001 changes no data).
--
-- Data only: the rows already in the database get the corrections made in
-- src/data/products.js, which reach new databases through the regenerated
-- seed. No schema, function or privilege changes.
--   (a) SKUs cut at 17 characters are completed, the four that ended in a
--       hyphen lose it, the misspelled ones are fixed and #329's bare
--       'AW-RAW' becomes 'AW-RAW-TIPS' (AW-135).
--   (b) Variant labels are spelled out and made consistent, #62's merged chip
--       is split, sizes run small to big, and one-item non-choices ("Case",
--       "Tips", "Mix", "Organic", "Small") are removed (AW-138); #60's
--       profane flavor is starred out (AW-126).
--   (c) The descriptions list the new labels; #354's size moves into its
--       name and #123/#124 say they are sold by the case.
--   (d) A variant's own price (product_variant_prices) and an "unavailable"
--       mark (products.unavailable_variants) follow a renamed label, because
--       the order trigger and my_prices() match them by label.
--
-- Each update changes a row only while it still holds exactly the value the
-- seed wrote (the old value in its VALUES list), so an admin's edit is never
-- overwritten, and running this file again changes nothing (AW-032).
--
-- Old keys keep working: src/data/catalogAliases.js maps every old SKU and
-- variant slug to the new one, in both directions, for stored carts, Quick
-- Reorder codes and Reorder from order history. order_items keep their
-- snapshots (sku, product_name, variant), so order history still shows the
-- codes and labels an order was placed with.
--
-- Release order: after 20260928121000_variant_model.sql, before the
-- regenerated seed and the frontend. The new frontend also works before this
-- migration (the aliases resolve the old labels and SKUs the live catalog
-- still has). Deploy it right after: the frontend deployed before it doesn't
-- know the new labels, so a quote it sends with a renamed variant is refused
-- by the order trigger ("Unknown variant").

-- ---------------------------------------------------------------------------
-- (a) SKUs (AW-135).
-- ---------------------------------------------------------------------------
update public.products as p
set sku = v.new_sku
from (values
  (12, 'AW-LOOSE-LEAFS-2P', 'AW-LOOSE-LEAFS-2PK'),
  (15, 'AW-ROYAL-BUNTS-MI', 'AW-ROYAL-BLUNTS-MINI'),
  (16, 'AW-BACKWOODS-SING', 'AW-BACKWOODS-SINGLES'),
  (28, 'AW-RHINO-PILLS-2P', 'AW-RHINO-PILLS-2PK'),
  (38, 'AW-WRIGGLY-SLIM-P', 'AW-WRIGLEY-SLIM-PACK'),
  (40, 'AW-WRIGGLY-50', 'AW-WRIGLEY-50'),
  (45, 'AW-ARGO-CORN-STAR', 'AW-ARGO-CORN-STARCH'),
  (65, 'AW-RAZ-VUE-FULL-K', 'AW-RAZ-VUE-FULL-KIT'),
  (69, 'AW-SHROOM-PUFF-DI', 'AW-SHROOM-PUFF-DISPOSABLE'),
  (72, 'AW-SHROOM-PUFF-GU', 'AW-SHROOM-PUFF-GUMMIES'),
  (84, 'AW-GOOD-TIMES-FLA', 'AW-GOOD-TIMES-FLAT'),
  (93, 'AW-6PK-BEER-CARRI', 'AW-6PK-BEER-CARRIERS'),
  (95, 'AW-TRASH-CAN-LINE', 'AW-TRASH-CAN-LINERS'),
  (99, 'AW-PEAK-ANTIFREEZ', 'AW-PEAK-ANTIFREEZE'),
  (100, 'AW-CHEAP-ANTIFREE', 'AW-CHEAP-ANTIFREEZE'),
  (103, 'AW-WINDSHIELD-WAS', 'AW-WINDSHIELD-WASHER'),
  (109, 'AW-AJAX-DISHWASHE', 'AW-AJAX-DISH-LIQUID'),
  (110, 'AW-BRILLO-DISHWAS', 'AW-BRILLO-DISH-LIQUID'),
  (116, 'AW-IRISH-SPRING-S', 'AW-IRISH-SPRING-SOAP'),
  (117, 'AW-AWESOME-LAUNDR', 'AW-AWESOME-LAUNDRY'),
  (128, 'AW-FABULOUSO', 'AW-FABULOSO'),
  (129, 'AW-HOME-AIR-FRESH', 'AW-HOME-AIR-FRESHENERS'),
  (130, 'AW-BRILLO-BASICS-', 'AW-BRILLO-BASICS'),
  (134, 'AW-RUBBING-ALCOHO', 'AW-RUBBING-ALCOHOL'),
  (138, 'AW-CHARCOAL-LIGHT', 'AW-CHARCOAL-LIGHTER'),
  (140, 'AW-TROPICANA-SMAL', 'AW-TROPICANA-SMALL'),
  (153, 'AW-WHITE-LONG-SLE', 'AW-WHITE-LONG-SLEEVE'),
  (154, 'AW-BLACK-LONG-SLE', 'AW-BLACK-LONG-SLEEVE'),
  (175, 'AW-CHICO-STICK-JA', 'AW-CHICK-O-STICK-JAR'),
  (179, 'AW-LAFFY-TAFFY-JA', 'AW-LAFFY-TAFFY-JAR'),
  (180, 'AW-LAFFY-TAFFY-RO', 'AW-LAFFY-TAFFY-ROPES'),
  (207, 'AW-20OZ-MINUTE-MA', 'AW-20OZ-MINUTE-MAID'),
  (208, 'AW-12OZ-MINUTE-MA', 'AW-12OZ-MINUTE-MAID'),
  (219, 'AW-HAPPY-VALENTIN', 'AW-HAPPY-VALENTINES'),
  (222, 'AW-PEPCID-COMPLET', 'AW-PEPCID-COMPLETE'),
  (225, 'AW-WOMEN-DEODORAN', 'AW-WOMEN-DEODORANT'),
  (233, 'AW-NESQUICK', 'AW-NESQUIK'),
  (238, 'AW-GAMBLER-BAGS-B', 'AW-GAMBLER-BAGS-BIG'),
  (239, 'AW-GAMBLER-BAGS-S', 'AW-GAMBLER-BAGS-SMALL'),
  (245, 'AW-BLUNTEFFECT-IN', 'AW-BLUNTEFFECT-INCENSE'),
  (247, 'AW-LATTAFA-AIR-FR', 'AW-LATTAFA-AIR-FRESHENER'),
  (258, 'AW-PSYCHED-PRE-RO', 'AW-PSYCHED-PRE-ROLLS'),
  (266, 'AW-BLUE-WOLF-HONE', 'AW-BLUE-WOLF-HONEY'),
  (271, 'AW-SNICKERS-CHOCO', 'AW-SNICKERS-CHOCOLATE'),
  (273, 'AW-LOOSE-LEAFS-SP', 'AW-LOOSE-LEAFS-SPLITS'),
  (274, 'AW-RAW-GUARANA-WR', 'AW-RAW-GUARANA-WRAPS'),
  (275, 'AW-JOLLY-RANCHER-', 'AW-JOLLY-RANCHER'),
  (276, 'AW-NOW-AND-LATER-', 'AW-NOW-AND-LATER-GIANT'),
  (281, 'AW-HUSH-HIT-PRE-R', 'AW-HUSH-HIT-PRE-ROLLS'),
  (285, 'AW-SHROOM-BANG-PR', 'AW-SHROOM-BANG-PRE-ROLLS'),
  (286, 'AW-AA-CELLULAR-BL', 'AW-AA-CELLULAR-BLUETOOTH'),
  (288, 'AW-BLUE-MONKEY-PR', 'AW-BLUE-MONKEY-PRE-ROLLS'),
  (289, 'AW-PSYCHED-DISPOS', 'AW-PSYCHED-DISPOSABLE'),
  (292, 'AW-ELECTROLYTE', 'AW-ELECTROLIT'),
  (296, 'AW-JELLY-HOLES-PR', 'AW-JELLY-HOLES-PRE-ROLLS'),
  (298, 'AW-SHROOM-ROLLS-P', 'AW-SHROOM-ROLLS-PRE-ROLLS'),
  (300, 'AW-MELTED-MUSHROO', 'AW-MELTED-MUSHROOM'),
  (302, 'AW-BETTER-ME-PILL', 'AW-BETTER-ME-PILLS'),
  (303, 'AW-HIGH-GRAVITY-P', 'AW-HIGH-GRAVITY-PILLS'),
  (304, 'AW-THIRD-EYE-PILL', 'AW-THIRD-EYE-PILLS'),
  (306, 'AW-STONED-MUSHROO', 'AW-STONED-MUSHROOM'),
  (307, 'AW-STONED-HONEY-M', 'AW-STONED-HONEY-MUSHROOM'),
  (311, 'AW-GEEKBAR-MATE-P', 'AW-GEEKBAR-MATE-PODS'),
  (312, 'AW-STONED-BLUE-LO', 'AW-STONED-BLUE-LOTUS'),
  (313, 'AW-PSYCHED-BLUE-L', 'AW-PSYCHED-BLUE-LOTUS'),
  (314, 'AW-COCO-NARA-CHAR', 'AW-COCO-NARA-CHARCOAL'),
  (315, 'AW-ALFAKHER-50-GR', 'AW-ALFAKHER-50-GRAM'),
  (316, 'AW-ALFAKHER-250-G', 'AW-ALFAKHER-250-GRAM'),
  (323, 'AW-BEER-SALTS-BOT', 'AW-BEER-SALTS-BOTTLES'),
  (324, 'AW-BEER-SALTS-PAC', 'AW-BEER-SALTS-PACKETS'),
  (329, 'AW-RAW', 'AW-RAW-TIPS'),
  (332, 'AW-BLACK-TIGER-HO', 'AW-BLACK-TIGER-HONEY'),
  (333, 'AW-GAIN-DISHWASHE', 'AW-GAIN-DISH-LIQUID'),
  (337, 'AW-BOB-MARLEY-PAP', 'AW-BOB-MARLEY-PAPERS'),
  (339, 'AW-BILLIONAIRE-WR', 'AW-BILLIONAIRE-WRAPS'),
  (340, 'AW-SLAPWOODS-SING', 'AW-SLAPWOODS-SINGLES'),
  (341, 'AW-SILLY-DOTS-PIL', 'AW-SILLY-DOTS-PILLS'),
  (342, 'AW-DUBAI-CHOCOLAT', 'AW-DUBAI-CHOCOLATE'),
  (347, 'AW-ZIGZAG-HEMP-WR', 'AW-ZIGZAG-HEMP-WRAPS'),
  (351, 'AW-UNCLE-AL-S-COO', 'AW-UNCLE-AL-S-COOKIES'),
  (352, 'AW-LOUISIANA-HOT-', 'AW-LOUISIANA-HOT'),
  (357, 'AW-STARBUST-BARS', 'AW-STARBURST-BARS'),
  (358, 'AW-LIFESAVER-SHAR', 'AW-LIFESAVER-SHARE'),
  (361, 'AW-DOMINOES-SUGAR', 'AW-DOMINO-SUGAR'),
  (362, 'AW-DISPOSABLE-GLO', 'AW-DISPOSABLE-GLOVES'),
  (367, 'AW-LOOSE-LEAFS-5P', 'AW-LOOSE-LEAFS-5PK')
) as v(id, old_sku, new_sku)
where p.id = v.id and p.sku = v.old_sku;

-- ---------------------------------------------------------------------------
-- (b) Variant labels (AW-138, AW-126). A list changes only while it is
-- exactly the list the seed wrote. No variant_axis changes: the rows that
-- lose their variants never had an axis.
-- ---------------------------------------------------------------------------
update public.products as p
set variants = v.new_variants
from (values
  (12,
   '["Cinnamon milk", "Sweet", "Honey", "Cookies cream", "Natural", "Amber dream"]'::jsonb,
   '["Cinnamon milk", "Sweet", "Honey", "Cookies & cream", "Natural", "Amber dream"]'::jsonb),
  (27,
   '["9V", "AAA4", "AA4", "D2", "AAA2", "AA2", "C2"]'::jsonb,
   '["9V", "AAA 4-pack", "AA 4-pack", "D 2-pack", "AAA 2-pack", "AA 2-pack", "C 2-pack"]'::jsonb),
  (51,
   '["Frosted Flakes", "Apple jack", "Froot Loops", "Corn Pops"]'::jsonb,
   '["Frosted Flakes", "Apple Jacks", "Froot Loops", "Corn Pops"]'::jsonb),
  (52,
   '["Butter flies", "Circus peanuts", "Watermelon rings", "Gummy worms"]'::jsonb,
   '["Butterflies", "Circus peanuts", "Watermelon rings", "Gummy worms"]'::jsonb),
  (60,
   '["Blue razz ice", "Fuckin fab"]'::jsonb,
   '["Blue razz ice", "F*** fab"]'::jsonb),
  (62,
   '["Coconut cupcake", "Strawberry kiwi", "Red velvet cupcake", "Watermelon ice Kiwi dragon berry", "Mexico mango", "Omg b burst", "White gummy", "Blue rancher"]'::jsonb,
   '["Coconut cupcake", "Strawberry kiwi", "Red velvet cupcake", "Watermelon ice", "Kiwi dragon berry", "Mexico mango", "Omg b burst", "White gummy", "Blue rancher"]'::jsonb),
  (63,
   '["Sour Apple ice", "Vanilla ice cream", "Pineapple coconut", "Kiwi dragon berry", "White gummy", "California cherry", "Strawberry watermelon", "Strawberry ice"]'::jsonb,
   '["Sour apple ice", "Vanilla ice cream", "Pineapple coconut", "Kiwi dragon berry", "White gummy", "California cherry", "Strawberry watermelon", "Strawberry ice"]'::jsonb),
  (107,
   '["13gal", "23gal", "Kitchen", "Lawn"]'::jsonb,
   '["13 gal", "23 gal", "Kitchen", "Lawn"]'::jsonb),
  (120,
   '["20oz", "16oz", "12oz", "8oz"]'::jsonb,
   '["20 oz", "16 oz", "12 oz", "8 oz"]'::jsonb),
  (122,
   '["Case"]'::jsonb,
   '[]'::jsonb),
  (123,
   '["Case"]'::jsonb,
   '[]'::jsonb),
  (124,
   '["Case"]'::jsonb,
   '[]'::jsonb),
  (125,
   '["Big", "Small", "Medium"]'::jsonb,
   '["Small", "Medium", "Big"]'::jsonb),
  (150,
   '["IPhone", "Type C", "Android", "Car charger", "Home charger", "IPhone To type C", "Type C To Type C", "Home charger with type C"]'::jsonb,
   '["iPhone (Lightning)", "USB-C", "Android", "Car charger", "Home charger", "Lightning to USB-C", "USB-C to USB-C", "Home charger with USB-C"]'::jsonb),
  (162,
   '["Regular", "King size", "Almond reg", "Almond king size"]'::jsonb,
   '["Regular", "King size", "Almond, regular", "Almond, king size"]'::jsonb),
  (163,
   '["Yellow reg", "Yellow share size", "Chocolate reg", "Chocolate king size"]'::jsonb,
   '["Yellow, regular", "Yellow, share size", "Chocolate, regular", "Chocolate, king size"]'::jsonb),
  (164,
   '["Regular", "King size", "Vanilla reg", "Vanilla king size"]'::jsonb,
   '["Regular", "King size", "Vanilla, regular", "Vanilla, king size"]'::jsonb),
  (166,
   '["Cups regular", "Cups king size", "White cups reg", "White cups king size", "Pieces reg", "Pieces king size", "Fast break reg", "Fast break king size"]'::jsonb,
   '["Cups, regular", "Cups, king size", "White cups, regular", "White cups, king size", "Pieces, regular", "Pieces, king size", "Fast break, regular", "Fast break, king size"]'::jsonb),
  (169,
   '["Red reg", "Red king size", "Wildberry reg", "Wildberry king size", "Sour reg", "Sour king size", "Blue reg", "Blue king size"]'::jsonb,
   '["Red, regular", "Red, king size", "Wildberry, regular", "Wildberry, king size", "Sour, regular", "Sour, king size", "Blue, regular", "Blue, king size"]'::jsonb),
  (171,
   '["Milk reg", "Milk king size", "Cookies reg", "Cookies king", "Almond reg", "Almond king", "Mr. Goodbar reg", "Mr. Goodbar king"]'::jsonb,
   '["Milk, regular", "Milk, king size", "Cookies, regular", "Cookies, king size", "Almond, regular", "Almond, king size", "Mr. Goodbar, regular", "Mr. Goodbar, king size"]'::jsonb),
  (183,
   '["Watermelon", "Spearmint", "Peppermint", "Polar ice", "Winter fresh"]'::jsonb,
   '["Watermelon", "Spearmint", "Peppermint", "Polar ice", "Winterfresh"]'::jsonb),
  (201,
   '["5-flavors", "Collision", "Wildberry", "Sours", "Fruit rings", "XO rings", "Exotics"]'::jsonb,
   '["5 Flavors", "Collision", "Wildberry", "Sours", "Fruit rings", "XO rings", "Exotics"]'::jsonb),
  (212,
   '["8lbs", "10lbs"]'::jsonb,
   '["8 lb", "10 lb"]'::jsonb),
  (242,
   '["Gold 100", "Gold king", "Menthol 100", "Menthol king", "Red 100", "Red king"]'::jsonb,
   '["Gold 100", "Gold king size", "Menthol 100", "Menthol king size", "Red 100", "Red king size"]'::jsonb),
  (243,
   '["Gold 100", "Gold king", "Menthol 100", "Menthol king", "Orange 100", "Orange king", "Silver 100", "Silver king"]'::jsonb,
   '["Gold 100", "Gold king size", "Menthol 100", "Menthol king size", "Orange 100", "Orange king size", "Silver 100", "Silver king size"]'::jsonb),
  (267,
   '["Mix"]'::jsonb,
   '[]'::jsonb),
  (314,
   '["Big", "Small", "Medium", "1kg"]'::jsonb,
   '["Small", "Medium", "Big", "1 kg"]'::jsonb),
  (329,
   '["Tips"]'::jsonb,
   '[]'::jsonb),
  (330,
   '["Organic"]'::jsonb,
   '[]'::jsonb),
  (331,
   '["AAA2"]'::jsonb,
   '["AAA 2-pack"]'::jsonb),
  (354,
   '["Small"]'::jsonb,
   '[]'::jsonb),
  (356,
   '["1 gal", "2gal", "5 gal"]'::jsonb,
   '["1 gal", "2 gal", "5 gal"]'::jsonb),
  (362,
   '["M size", "L size"]'::jsonb,
   '["Medium", "Large"]'::jsonb)
) as v(id, old_variants, new_variants)
where p.id = v.id and p.variants = v.old_variants;

-- ---------------------------------------------------------------------------
-- (c) Descriptions, names and sell units.
-- ---------------------------------------------------------------------------
update public.products as p
set description = v.new_text
from (values
  (12,
   'LooseLeaf flavored wraps in 2-packs, stocked at the $2.99 and $1.99 price points. Six flavors: Cinnamon milk, Sweet, Honey, Cookies cream, Natural and Amber dream.',
   'LooseLeaf flavored wraps in 2-packs, stocked at the $2.99 and $1.99 price points. Six flavors: Cinnamon milk, Sweet, Honey, Cookies & cream, Natural and Amber dream.'),
  (27,
   'Duracell alkaline batteries in carded packs. Seven sizes: 9V, AAA4, AA4, D2, AAA2, AA2 and C2.',
   'Duracell alkaline batteries in carded packs. Seven sizes: 9V, AAA 4-pack, AA 4-pack, D 2-pack, AAA 2-pack, AA 2-pack and C 2-pack.'),
  (51,
   'Single-serve cereal cups. Four varieties: Frosted Flakes, Apple jack, Froot Loops and Corn Pops.',
   'Single-serve cereal cups. Four varieties: Frosted Flakes, Apple Jacks, Froot Loops and Corn Pops.'),
  (52,
   'Gurley''s candy peg bags. Four varieties: Butter flies, Circus peanuts, Watermelon rings and Gummy worms.',
   'Gurley''s candy peg bags. Four varieties: Butterflies, Circus peanuts, Watermelon rings and Gummy worms.'),
  (60,
   'Geek Bar Pulse 15,000-puff disposable vape. Two flavors: Blue razz ice and Fuckin fab.',
   'Geek Bar Pulse 15,000-puff disposable vape. Two flavors: Blue razz ice and F*** fab.'),
  (62,
   'Foger Switch Pro disposable and power bank, full kit. Eight flavors: Coconut cupcake, Strawberry kiwi, Red velvet cupcake, Watermelon ice Kiwi dragon berry, Mexico mango, Omg b burst, White gummy and Blue rancher.',
   'Foger Switch Pro disposable and power bank, full kit. Nine flavors: Coconut cupcake, Strawberry kiwi, Red velvet cupcake, Watermelon ice, Kiwi dragon berry, Mexico mango, Omg b burst, White gummy and Blue rancher.'),
  (63,
   'Foger Switch Pro replacement pods for the Switch Pro charging device. Eight flavors: Sour Apple ice, Vanilla ice cream, Pineapple coconut, Kiwi dragon berry, White gummy, California cherry, Strawberry watermelon and Strawberry ice.',
   'Foger Switch Pro replacement pods for the Switch Pro charging device. Eight flavors: Sour apple ice, Vanilla ice cream, Pineapple coconut, Kiwi dragon berry, White gummy, California cherry, Strawberry watermelon and Strawberry ice.'),
  (107,
   'Trash bags from the bags and storage line in our Grocery department. Four varieties: 13gal, 23gal, Kitchen and Lawn.',
   'Trash bags from the bags and storage line in our Grocery department. Four varieties: 13 gal, 23 gal, Kitchen and Lawn.'),
  (120,
   'Insulated foam cups. Four sizes: 20oz, 16oz, 12oz and 8oz.',
   'Insulated foam cups. Four sizes: 20 oz, 16 oz, 12 oz and 8 oz.'),
  (122,
   'Bath tissue in 4-roll packs. Stocked in one variety: Case.',
   'Bath tissue in 4-roll packs, stocked by the case.'),
  (123,
   'Paper towel rolls. Stocked in one variety: Case.',
   'Paper towel rolls, sold by the case.'),
  (124,
   'Bath tissue in single rolls. Stocked in one variety: Case.',
   'Bath tissue in single rolls, sold by the case.'),
  (125,
   'Baby diapers from the personal care line in our Grocery department. Three sizes: Big, Small and Medium.',
   'Baby diapers from the personal care line in our Grocery department. Three sizes: Small, Medium and Big.'),
  (150,
   'Phone cables and chargers for the counter display. Eight types: IPhone, Type C, Android, Car charger, Home charger, IPhone To type C, Type C To Type C and Home charger with type C.',
   'Phone cables and chargers for the counter display. Eight types: iPhone (Lightning), USB-C, Android, Car charger, Home charger, Lightning to USB-C, USB-C to USB-C and Home charger with USB-C.'),
  (162,
   'Snickers candy bars. Four varieties: Regular, King size, Almond reg and Almond king size.',
   'Snickers candy bars. Four varieties: Regular; King size; Almond, regular; and Almond, king size.'),
  (163,
   'M&M''s chocolate candies. Four varieties: Yellow reg, Yellow share size, Chocolate reg and Chocolate king size.',
   'M&M''s chocolate candies. Four varieties: Yellow, regular; Yellow, share size; Chocolate, regular; and Chocolate, king size.'),
  (164,
   'Kit Kat wafer bars. Four varieties: Regular, King size, Vanilla reg and Vanilla king size.',
   'Kit Kat wafer bars. Four varieties: Regular; King size; Vanilla, regular; and Vanilla, king size.'),
  (166,
   'Reese''s peanut butter candy. Eight varieties: Cups regular, Cups king size, White cups reg, White cups king size, Pieces reg, Pieces king size, Fast break reg and Fast break king size.',
   'Reese''s peanut butter candy. Eight varieties: Cups, regular; Cups, king size; White cups, regular; White cups, king size; Pieces, regular; Pieces, king size; Fast break, regular; and Fast break, king size.'),
  (169,
   'Skittles chewy candy. Eight varieties: Red reg, Red king size, Wildberry reg, Wildberry king size, Sour reg, Sour king size, Blue reg and Blue king size.',
   'Skittles chewy candy. Eight varieties: Red, regular; Red, king size; Wildberry, regular; Wildberry, king size; Sour, regular; Sour, king size; Blue, regular; and Blue, king size.'),
  (171,
   'Hershey''s chocolate bars. Eight varieties: Milk reg, Milk king size, Cookies reg, Cookies king, Almond reg, Almond king, Mr. Goodbar reg and Mr. Goodbar king.',
   'Hershey''s chocolate bars. Eight varieties: Milk, regular; Milk, king size; Cookies, regular; Cookies, king size; Almond, regular; Almond, king size; Mr. Goodbar, regular; and Mr. Goodbar, king size.'),
  (183,
   'Extra gum from the gum and mints line in our Candies department. Five flavors: Watermelon, Spearmint, Peppermint, Polar ice and Winter fresh.',
   'Extra gum from the gum and mints line in our Candies department. Five flavors: Watermelon, Spearmint, Peppermint, Polar ice and Winterfresh.'),
  (201,
   'Life Savers Gummies peg bags. Seven varieties: 5-flavors, Collision, Wildberry, Sours, Fruit rings, XO rings and Exotics.',
   'Life Savers Gummies peg bags. Seven varieties: 5 Flavors, Collision, Wildberry, Sours, Fruit rings, XO rings and Exotics.'),
  (212,
   'Ice bags from the bags and carriers line in our Drinks & Bags department. Two sizes: 8lbs and 10lbs.',
   'Ice bags from the bags and carriers line in our Drinks & Bags department. Two sizes: 8 lb and 10 lb.'),
  (242,
   'Gambler cigarette filter tubes, 200 per box. Six varieties: Gold 100, Gold king, Menthol 100, Menthol king, Red 100 and Red king.',
   'Gambler cigarette filter tubes, 200 per box. Six varieties: Gold 100, Gold king size, Menthol 100, Menthol king size, Red 100 and Red king size.'),
  (243,
   'Gambler Tube Cut cigarette filter tubes, 200 per box. Eight varieties: Gold 100, Gold king, Menthol 100, Menthol king, Orange 100, Orange king, Silver 100 and Silver king.',
   'Gambler Tube Cut cigarette filter tubes, 200 per box. Eight varieties: Gold 100, Gold king size, Menthol 100, Menthol king size, Orange 100, Orange king size, Silver 100 and Silver king size.'),
  (267,
   'ZYN nicotine pouches, European assortment. Stocked in one variety: Mix.',
   'ZYN nicotine pouches, European assortment.'),
  (314,
   'Coco Nara coconut hookah charcoal. Four sizes: Big, Small, Medium and 1kg.',
   'Coco Nara coconut hookah charcoal. Four sizes: Small, Medium, Big and 1 kg.'),
  (329,
   'RAW rolling tips from the papers and cones line in our Tobacco department. Stocked in one variety: Tips.',
   'RAW rolling tips from the papers and cones line in our Tobacco department.'),
  (330,
   'High Hemp organic hemp wraps. Stocked in one variety: Organic.',
   'High Hemp organic hemp wraps.'),
  (331,
   'Panasonic batteries in carded packs. Stocked in one variety: AAA2.',
   'Panasonic batteries in carded packs. Stocked in one variety: AAA 2-pack.'),
  (354,
   'Folgers coffee from the coffee line in our Food Stuff department. Stocked in one variety: Small.',
   'Folgers coffee in the small size, from the coffee line in our Food Stuff department.'),
  (356,
   'Gas cans from the auto accessory line in our Motor Oil department. Three sizes: 1 gal, 2gal and 5 gal.',
   'Gas cans from the auto accessory line in our Motor Oil department. Three sizes: 1 gal, 2 gal and 5 gal.'),
  (362,
   'Disposable gloves. Two sizes: M size and L size.',
   'Disposable gloves. Two sizes: Medium and Large.')
) as v(id, old_text, new_text)
where p.id = v.id and p.description = v.old_text;

-- #354's only variant was its size.
update public.products as p
set name = v.new_name
from (values
  (354, 'Folgers coffee', 'Folgers coffee (small)')
) as v(id, old_name, new_name)
where p.id = v.id and p.name = v.old_name;

-- "Case" was the only variant of #123 and #124.
-- TODO(owner): Is quantity 1 of #122-#124 a case, and how many packs or rolls are in one? (AW-138)
update public.products as p
set sell_unit = v.new_unit
from (values
  (123, '', 'case'),
  (124, '', 'case')
) as v(id, old_unit, new_unit)
where p.id = v.id and p.sell_unit = v.old_unit;

-- ---------------------------------------------------------------------------
-- (d) A renamed variant keeps its own price and its "not available" mark.
-- Only on rows whose list (b) changed to the new labels, and never onto a
-- label that already has its own price row.
-- ---------------------------------------------------------------------------
update public.product_variant_prices as vp
set variant = v.new_label
from (values
  (12, 'Cookies cream', 'Cookies & cream'),
  (27, 'AAA4', 'AAA 4-pack'),
  (27, 'AA4', 'AA 4-pack'),
  (27, 'D2', 'D 2-pack'),
  (27, 'AAA2', 'AAA 2-pack'),
  (27, 'AA2', 'AA 2-pack'),
  (27, 'C2', 'C 2-pack'),
  (51, 'Apple jack', 'Apple Jacks'),
  (52, 'Butter flies', 'Butterflies'),
  (60, 'Fuckin fab', 'F*** fab'),
  (107, '13gal', '13 gal'),
  (107, '23gal', '23 gal'),
  (120, '20oz', '20 oz'),
  (120, '16oz', '16 oz'),
  (120, '12oz', '12 oz'),
  (120, '8oz', '8 oz'),
  (150, 'IPhone', 'iPhone (Lightning)'),
  (150, 'Type C', 'USB-C'),
  (150, 'IPhone To type C', 'Lightning to USB-C'),
  (150, 'Type C To Type C', 'USB-C to USB-C'),
  (150, 'Home charger with type C', 'Home charger with USB-C'),
  (162, 'Almond reg', 'Almond, regular'),
  (162, 'Almond king size', 'Almond, king size'),
  (163, 'Yellow reg', 'Yellow, regular'),
  (163, 'Yellow share size', 'Yellow, share size'),
  (163, 'Chocolate reg', 'Chocolate, regular'),
  (163, 'Chocolate king size', 'Chocolate, king size'),
  (164, 'Vanilla reg', 'Vanilla, regular'),
  (164, 'Vanilla king size', 'Vanilla, king size'),
  (166, 'Cups regular', 'Cups, regular'),
  (166, 'Cups king size', 'Cups, king size'),
  (166, 'White cups reg', 'White cups, regular'),
  (166, 'White cups king size', 'White cups, king size'),
  (166, 'Pieces reg', 'Pieces, regular'),
  (166, 'Pieces king size', 'Pieces, king size'),
  (166, 'Fast break reg', 'Fast break, regular'),
  (166, 'Fast break king size', 'Fast break, king size'),
  (169, 'Red reg', 'Red, regular'),
  (169, 'Red king size', 'Red, king size'),
  (169, 'Wildberry reg', 'Wildberry, regular'),
  (169, 'Wildberry king size', 'Wildberry, king size'),
  (169, 'Sour reg', 'Sour, regular'),
  (169, 'Sour king size', 'Sour, king size'),
  (169, 'Blue reg', 'Blue, regular'),
  (169, 'Blue king size', 'Blue, king size'),
  (171, 'Milk reg', 'Milk, regular'),
  (171, 'Milk king size', 'Milk, king size'),
  (171, 'Cookies reg', 'Cookies, regular'),
  (171, 'Cookies king', 'Cookies, king size'),
  (171, 'Almond reg', 'Almond, regular'),
  (171, 'Almond king', 'Almond, king size'),
  (171, 'Mr. Goodbar reg', 'Mr. Goodbar, regular'),
  (171, 'Mr. Goodbar king', 'Mr. Goodbar, king size'),
  (183, 'Winter fresh', 'Winterfresh'),
  (201, '5-flavors', '5 Flavors'),
  (212, '8lbs', '8 lb'),
  (212, '10lbs', '10 lb'),
  (242, 'Gold king', 'Gold king size'),
  (242, 'Menthol king', 'Menthol king size'),
  (242, 'Red king', 'Red king size'),
  (243, 'Gold king', 'Gold king size'),
  (243, 'Menthol king', 'Menthol king size'),
  (243, 'Orange king', 'Orange king size'),
  (243, 'Silver king', 'Silver king size'),
  (314, '1kg', '1 kg'),
  (331, 'AAA2', 'AAA 2-pack'),
  (356, '2gal', '2 gal'),
  (362, 'M size', 'Medium'),
  (362, 'L size', 'Large')
) as v(product_id, old_label, new_label)
where vp.product_id = v.product_id
  and lower(vp.variant) = lower(v.old_label)
  and exists (
    select 1 from public.products as p
    where p.id = v.product_id and p.variants ? v.new_label and not p.variants ? v.old_label
  )
  and not exists (
    select 1 from public.product_variant_prices as other
    where other.product_id = v.product_id and lower(other.variant) = lower(v.new_label)
  );

-- One row per product: lower(old label) -> new label.
update public.products as p
set unavailable_variants = (
  select coalesce(jsonb_agg(coalesce(v.renames -> lower(u.label), to_jsonb(u.label)) order by u.ord), '[]'::jsonb)
  from jsonb_array_elements_text(p.unavailable_variants) with ordinality as u(label, ord)
)
from (values
  (12, '{"cookies cream":"Cookies & cream"}'::jsonb),
  (27, '{"aaa4":"AAA 4-pack","aa4":"AA 4-pack","d2":"D 2-pack","aaa2":"AAA 2-pack","aa2":"AA 2-pack","c2":"C 2-pack"}'::jsonb),
  (51, '{"apple jack":"Apple Jacks"}'::jsonb),
  (52, '{"butter flies":"Butterflies"}'::jsonb),
  (60, '{"fuckin fab":"F*** fab"}'::jsonb),
  (107, '{"13gal":"13 gal","23gal":"23 gal"}'::jsonb),
  (120, '{"20oz":"20 oz","16oz":"16 oz","12oz":"12 oz","8oz":"8 oz"}'::jsonb),
  (150, '{"iphone":"iPhone (Lightning)","type c":"USB-C","iphone to type c":"Lightning to USB-C","type c to type c":"USB-C to USB-C","home charger with type c":"Home charger with USB-C"}'::jsonb),
  (162, '{"almond reg":"Almond, regular","almond king size":"Almond, king size"}'::jsonb),
  (163, '{"yellow reg":"Yellow, regular","yellow share size":"Yellow, share size","chocolate reg":"Chocolate, regular","chocolate king size":"Chocolate, king size"}'::jsonb),
  (164, '{"vanilla reg":"Vanilla, regular","vanilla king size":"Vanilla, king size"}'::jsonb),
  (166, '{"cups regular":"Cups, regular","cups king size":"Cups, king size","white cups reg":"White cups, regular","white cups king size":"White cups, king size","pieces reg":"Pieces, regular","pieces king size":"Pieces, king size","fast break reg":"Fast break, regular","fast break king size":"Fast break, king size"}'::jsonb),
  (169, '{"red reg":"Red, regular","red king size":"Red, king size","wildberry reg":"Wildberry, regular","wildberry king size":"Wildberry, king size","sour reg":"Sour, regular","sour king size":"Sour, king size","blue reg":"Blue, regular","blue king size":"Blue, king size"}'::jsonb),
  (171, '{"milk reg":"Milk, regular","milk king size":"Milk, king size","cookies reg":"Cookies, regular","cookies king":"Cookies, king size","almond reg":"Almond, regular","almond king":"Almond, king size","mr. goodbar reg":"Mr. Goodbar, regular","mr. goodbar king":"Mr. Goodbar, king size"}'::jsonb),
  (183, '{"winter fresh":"Winterfresh"}'::jsonb),
  (201, '{"5-flavors":"5 Flavors"}'::jsonb),
  (212, '{"8lbs":"8 lb","10lbs":"10 lb"}'::jsonb),
  (242, '{"gold king":"Gold king size","menthol king":"Menthol king size","red king":"Red king size"}'::jsonb),
  (243, '{"gold king":"Gold king size","menthol king":"Menthol king size","orange king":"Orange king size","silver king":"Silver king size"}'::jsonb),
  (314, '{"1kg":"1 kg"}'::jsonb),
  (331, '{"aaa2":"AAA 2-pack"}'::jsonb),
  (356, '{"2gal":"2 gal"}'::jsonb),
  (362, '{"m size":"Medium","l size":"Large"}'::jsonb)
) as v(id, renames)
where p.id = v.id
  and exists (
    select 1 from jsonb_array_elements_text(p.unavailable_variants) as u(label)
    where v.renames ? lower(u.label)
  )
  and not exists (
    select 1 from jsonb_each_text(v.renames) as r(old_label, new_label)
    where not p.variants ? r.new_label
  );

-- ---------------------------------------------------------------------------
-- (e) Reverse (AW-213). Not run; copy into the SQL editor to undo this
-- migration. Each statement puts back the old value only where the row still
-- has the new one. Deploy the previous frontend first (the new one also works
-- with the old values).
--
-- update public.product_variant_prices as vp
-- set variant = v.old_label
-- from (values
--   (12, 'Cookies cream', 'Cookies & cream'),
--   (27, 'AAA4', 'AAA 4-pack'),
--   (27, 'AA4', 'AA 4-pack'),
--   (27, 'D2', 'D 2-pack'),
--   (27, 'AAA2', 'AAA 2-pack'),
--   (27, 'AA2', 'AA 2-pack'),
--   (27, 'C2', 'C 2-pack'),
--   (51, 'Apple jack', 'Apple Jacks'),
--   (52, 'Butter flies', 'Butterflies'),
--   (60, 'Fuckin fab', 'F*** fab'),
--   (107, '13gal', '13 gal'),
--   (107, '23gal', '23 gal'),
--   (120, '20oz', '20 oz'),
--   (120, '16oz', '16 oz'),
--   (120, '12oz', '12 oz'),
--   (120, '8oz', '8 oz'),
--   (150, 'IPhone', 'iPhone (Lightning)'),
--   (150, 'Type C', 'USB-C'),
--   (150, 'IPhone To type C', 'Lightning to USB-C'),
--   (150, 'Type C To Type C', 'USB-C to USB-C'),
--   (150, 'Home charger with type C', 'Home charger with USB-C'),
--   (162, 'Almond reg', 'Almond, regular'),
--   (162, 'Almond king size', 'Almond, king size'),
--   (163, 'Yellow reg', 'Yellow, regular'),
--   (163, 'Yellow share size', 'Yellow, share size'),
--   (163, 'Chocolate reg', 'Chocolate, regular'),
--   (163, 'Chocolate king size', 'Chocolate, king size'),
--   (164, 'Vanilla reg', 'Vanilla, regular'),
--   (164, 'Vanilla king size', 'Vanilla, king size'),
--   (166, 'Cups regular', 'Cups, regular'),
--   (166, 'Cups king size', 'Cups, king size'),
--   (166, 'White cups reg', 'White cups, regular'),
--   (166, 'White cups king size', 'White cups, king size'),
--   (166, 'Pieces reg', 'Pieces, regular'),
--   (166, 'Pieces king size', 'Pieces, king size'),
--   (166, 'Fast break reg', 'Fast break, regular'),
--   (166, 'Fast break king size', 'Fast break, king size'),
--   (169, 'Red reg', 'Red, regular'),
--   (169, 'Red king size', 'Red, king size'),
--   (169, 'Wildberry reg', 'Wildberry, regular'),
--   (169, 'Wildberry king size', 'Wildberry, king size'),
--   (169, 'Sour reg', 'Sour, regular'),
--   (169, 'Sour king size', 'Sour, king size'),
--   (169, 'Blue reg', 'Blue, regular'),
--   (169, 'Blue king size', 'Blue, king size'),
--   (171, 'Milk reg', 'Milk, regular'),
--   (171, 'Milk king size', 'Milk, king size'),
--   (171, 'Cookies reg', 'Cookies, regular'),
--   (171, 'Cookies king', 'Cookies, king size'),
--   (171, 'Almond reg', 'Almond, regular'),
--   (171, 'Almond king', 'Almond, king size'),
--   (171, 'Mr. Goodbar reg', 'Mr. Goodbar, regular'),
--   (171, 'Mr. Goodbar king', 'Mr. Goodbar, king size'),
--   (183, 'Winter fresh', 'Winterfresh'),
--   (201, '5-flavors', '5 Flavors'),
--   (212, '8lbs', '8 lb'),
--   (212, '10lbs', '10 lb'),
--   (242, 'Gold king', 'Gold king size'),
--   (242, 'Menthol king', 'Menthol king size'),
--   (242, 'Red king', 'Red king size'),
--   (243, 'Gold king', 'Gold king size'),
--   (243, 'Menthol king', 'Menthol king size'),
--   (243, 'Orange king', 'Orange king size'),
--   (243, 'Silver king', 'Silver king size'),
--   (314, '1kg', '1 kg'),
--   (331, 'AAA2', 'AAA 2-pack'),
--   (356, '2gal', '2 gal'),
--   (362, 'M size', 'Medium'),
--   (362, 'L size', 'Large')
-- ) as v(product_id, old_label, new_label)
-- where vp.product_id = v.product_id and lower(vp.variant) = lower(v.new_label)
--   and not exists (
--     select 1 from public.product_variant_prices as other
--     where other.product_id = v.product_id and lower(other.variant) = lower(v.old_label)
--   );
--
-- (The unavailable_variants renames are undone by hand: replace each new label
-- in the list above with its old one.)
--
-- update public.products as p set sell_unit = v.old_unit
-- from (values
--   (123, '', 'case'),
--   (124, '', 'case')
-- ) as v(id, old_unit, new_unit)
-- where p.id = v.id and p.sell_unit = v.new_unit;
--
-- update public.products as p set name = v.old_name
-- from (values
--   (354, 'Folgers coffee', 'Folgers coffee (small)')
-- ) as v(id, old_name, new_name)
-- where p.id = v.id and p.name = v.new_name;
--
-- update public.products as p set description = v.old_text
-- from (values
--   (12,
--    'LooseLeaf flavored wraps in 2-packs, stocked at the $2.99 and $1.99 price points. Six flavors: Cinnamon milk, Sweet, Honey, Cookies cream, Natural and Amber dream.',
--    'LooseLeaf flavored wraps in 2-packs, stocked at the $2.99 and $1.99 price points. Six flavors: Cinnamon milk, Sweet, Honey, Cookies & cream, Natural and Amber dream.'),
--   (27,
--    'Duracell alkaline batteries in carded packs. Seven sizes: 9V, AAA4, AA4, D2, AAA2, AA2 and C2.',
--    'Duracell alkaline batteries in carded packs. Seven sizes: 9V, AAA 4-pack, AA 4-pack, D 2-pack, AAA 2-pack, AA 2-pack and C 2-pack.'),
--   (51,
--    'Single-serve cereal cups. Four varieties: Frosted Flakes, Apple jack, Froot Loops and Corn Pops.',
--    'Single-serve cereal cups. Four varieties: Frosted Flakes, Apple Jacks, Froot Loops and Corn Pops.'),
--   (52,
--    'Gurley''s candy peg bags. Four varieties: Butter flies, Circus peanuts, Watermelon rings and Gummy worms.',
--    'Gurley''s candy peg bags. Four varieties: Butterflies, Circus peanuts, Watermelon rings and Gummy worms.'),
--   (60,
--    'Geek Bar Pulse 15,000-puff disposable vape. Two flavors: Blue razz ice and Fuckin fab.',
--    'Geek Bar Pulse 15,000-puff disposable vape. Two flavors: Blue razz ice and F*** fab.'),
--   (62,
--    'Foger Switch Pro disposable and power bank, full kit. Eight flavors: Coconut cupcake, Strawberry kiwi, Red velvet cupcake, Watermelon ice Kiwi dragon berry, Mexico mango, Omg b burst, White gummy and Blue rancher.',
--    'Foger Switch Pro disposable and power bank, full kit. Nine flavors: Coconut cupcake, Strawberry kiwi, Red velvet cupcake, Watermelon ice, Kiwi dragon berry, Mexico mango, Omg b burst, White gummy and Blue rancher.'),
--   (63,
--    'Foger Switch Pro replacement pods for the Switch Pro charging device. Eight flavors: Sour Apple ice, Vanilla ice cream, Pineapple coconut, Kiwi dragon berry, White gummy, California cherry, Strawberry watermelon and Strawberry ice.',
--    'Foger Switch Pro replacement pods for the Switch Pro charging device. Eight flavors: Sour apple ice, Vanilla ice cream, Pineapple coconut, Kiwi dragon berry, White gummy, California cherry, Strawberry watermelon and Strawberry ice.'),
--   (107,
--    'Trash bags from the bags and storage line in our Grocery department. Four varieties: 13gal, 23gal, Kitchen and Lawn.',
--    'Trash bags from the bags and storage line in our Grocery department. Four varieties: 13 gal, 23 gal, Kitchen and Lawn.'),
--   (120,
--    'Insulated foam cups. Four sizes: 20oz, 16oz, 12oz and 8oz.',
--    'Insulated foam cups. Four sizes: 20 oz, 16 oz, 12 oz and 8 oz.'),
--   (122,
--    'Bath tissue in 4-roll packs. Stocked in one variety: Case.',
--    'Bath tissue in 4-roll packs, stocked by the case.'),
--   (123,
--    'Paper towel rolls. Stocked in one variety: Case.',
--    'Paper towel rolls, sold by the case.'),
--   (124,
--    'Bath tissue in single rolls. Stocked in one variety: Case.',
--    'Bath tissue in single rolls, sold by the case.'),
--   (125,
--    'Baby diapers from the personal care line in our Grocery department. Three sizes: Big, Small and Medium.',
--    'Baby diapers from the personal care line in our Grocery department. Three sizes: Small, Medium and Big.'),
--   (150,
--    'Phone cables and chargers for the counter display. Eight types: IPhone, Type C, Android, Car charger, Home charger, IPhone To type C, Type C To Type C and Home charger with type C.',
--    'Phone cables and chargers for the counter display. Eight types: iPhone (Lightning), USB-C, Android, Car charger, Home charger, Lightning to USB-C, USB-C to USB-C and Home charger with USB-C.'),
--   (162,
--    'Snickers candy bars. Four varieties: Regular, King size, Almond reg and Almond king size.',
--    'Snickers candy bars. Four varieties: Regular; King size; Almond, regular; and Almond, king size.'),
--   (163,
--    'M&M''s chocolate candies. Four varieties: Yellow reg, Yellow share size, Chocolate reg and Chocolate king size.',
--    'M&M''s chocolate candies. Four varieties: Yellow, regular; Yellow, share size; Chocolate, regular; and Chocolate, king size.'),
--   (164,
--    'Kit Kat wafer bars. Four varieties: Regular, King size, Vanilla reg and Vanilla king size.',
--    'Kit Kat wafer bars. Four varieties: Regular; King size; Vanilla, regular; and Vanilla, king size.'),
--   (166,
--    'Reese''s peanut butter candy. Eight varieties: Cups regular, Cups king size, White cups reg, White cups king size, Pieces reg, Pieces king size, Fast break reg and Fast break king size.',
--    'Reese''s peanut butter candy. Eight varieties: Cups, regular; Cups, king size; White cups, regular; White cups, king size; Pieces, regular; Pieces, king size; Fast break, regular; and Fast break, king size.'),
--   (169,
--    'Skittles chewy candy. Eight varieties: Red reg, Red king size, Wildberry reg, Wildberry king size, Sour reg, Sour king size, Blue reg and Blue king size.',
--    'Skittles chewy candy. Eight varieties: Red, regular; Red, king size; Wildberry, regular; Wildberry, king size; Sour, regular; Sour, king size; Blue, regular; and Blue, king size.'),
--   (171,
--    'Hershey''s chocolate bars. Eight varieties: Milk reg, Milk king size, Cookies reg, Cookies king, Almond reg, Almond king, Mr. Goodbar reg and Mr. Goodbar king.',
--    'Hershey''s chocolate bars. Eight varieties: Milk, regular; Milk, king size; Cookies, regular; Cookies, king size; Almond, regular; Almond, king size; Mr. Goodbar, regular; and Mr. Goodbar, king size.'),
--   (183,
--    'Extra gum from the gum and mints line in our Candies department. Five flavors: Watermelon, Spearmint, Peppermint, Polar ice and Winter fresh.',
--    'Extra gum from the gum and mints line in our Candies department. Five flavors: Watermelon, Spearmint, Peppermint, Polar ice and Winterfresh.'),
--   (201,
--    'Life Savers Gummies peg bags. Seven varieties: 5-flavors, Collision, Wildberry, Sours, Fruit rings, XO rings and Exotics.',
--    'Life Savers Gummies peg bags. Seven varieties: 5 Flavors, Collision, Wildberry, Sours, Fruit rings, XO rings and Exotics.'),
--   (212,
--    'Ice bags from the bags and carriers line in our Drinks & Bags department. Two sizes: 8lbs and 10lbs.',
--    'Ice bags from the bags and carriers line in our Drinks & Bags department. Two sizes: 8 lb and 10 lb.'),
--   (242,
--    'Gambler cigarette filter tubes, 200 per box. Six varieties: Gold 100, Gold king, Menthol 100, Menthol king, Red 100 and Red king.',
--    'Gambler cigarette filter tubes, 200 per box. Six varieties: Gold 100, Gold king size, Menthol 100, Menthol king size, Red 100 and Red king size.'),
--   (243,
--    'Gambler Tube Cut cigarette filter tubes, 200 per box. Eight varieties: Gold 100, Gold king, Menthol 100, Menthol king, Orange 100, Orange king, Silver 100 and Silver king.',
--    'Gambler Tube Cut cigarette filter tubes, 200 per box. Eight varieties: Gold 100, Gold king size, Menthol 100, Menthol king size, Orange 100, Orange king size, Silver 100 and Silver king size.'),
--   (267,
--    'ZYN nicotine pouches, European assortment. Stocked in one variety: Mix.',
--    'ZYN nicotine pouches, European assortment.'),
--   (314,
--    'Coco Nara coconut hookah charcoal. Four sizes: Big, Small, Medium and 1kg.',
--    'Coco Nara coconut hookah charcoal. Four sizes: Small, Medium, Big and 1 kg.'),
--   (329,
--    'RAW rolling tips from the papers and cones line in our Tobacco department. Stocked in one variety: Tips.',
--    'RAW rolling tips from the papers and cones line in our Tobacco department.'),
--   (330,
--    'High Hemp organic hemp wraps. Stocked in one variety: Organic.',
--    'High Hemp organic hemp wraps.'),
--   (331,
--    'Panasonic batteries in carded packs. Stocked in one variety: AAA2.',
--    'Panasonic batteries in carded packs. Stocked in one variety: AAA 2-pack.'),
--   (354,
--    'Folgers coffee from the coffee line in our Food Stuff department. Stocked in one variety: Small.',
--    'Folgers coffee in the small size, from the coffee line in our Food Stuff department.'),
--   (356,
--    'Gas cans from the auto accessory line in our Motor Oil department. Three sizes: 1 gal, 2gal and 5 gal.',
--    'Gas cans from the auto accessory line in our Motor Oil department. Three sizes: 1 gal, 2 gal and 5 gal.'),
--   (362,
--    'Disposable gloves. Two sizes: M size and L size.',
--    'Disposable gloves. Two sizes: Medium and Large.')
-- ) as v(id, old_text, new_text)
-- where p.id = v.id and p.description = v.new_text;
--
-- update public.products as p set variants = v.old_variants
-- from (values
--   (12,
--    '["Cinnamon milk", "Sweet", "Honey", "Cookies cream", "Natural", "Amber dream"]'::jsonb,
--    '["Cinnamon milk", "Sweet", "Honey", "Cookies & cream", "Natural", "Amber dream"]'::jsonb),
--   (27,
--    '["9V", "AAA4", "AA4", "D2", "AAA2", "AA2", "C2"]'::jsonb,
--    '["9V", "AAA 4-pack", "AA 4-pack", "D 2-pack", "AAA 2-pack", "AA 2-pack", "C 2-pack"]'::jsonb),
--   (51,
--    '["Frosted Flakes", "Apple jack", "Froot Loops", "Corn Pops"]'::jsonb,
--    '["Frosted Flakes", "Apple Jacks", "Froot Loops", "Corn Pops"]'::jsonb),
--   (52,
--    '["Butter flies", "Circus peanuts", "Watermelon rings", "Gummy worms"]'::jsonb,
--    '["Butterflies", "Circus peanuts", "Watermelon rings", "Gummy worms"]'::jsonb),
--   (60,
--    '["Blue razz ice", "Fuckin fab"]'::jsonb,
--    '["Blue razz ice", "F*** fab"]'::jsonb),
--   (62,
--    '["Coconut cupcake", "Strawberry kiwi", "Red velvet cupcake", "Watermelon ice Kiwi dragon berry", "Mexico mango", "Omg b burst", "White gummy", "Blue rancher"]'::jsonb,
--    '["Coconut cupcake", "Strawberry kiwi", "Red velvet cupcake", "Watermelon ice", "Kiwi dragon berry", "Mexico mango", "Omg b burst", "White gummy", "Blue rancher"]'::jsonb),
--   (63,
--    '["Sour Apple ice", "Vanilla ice cream", "Pineapple coconut", "Kiwi dragon berry", "White gummy", "California cherry", "Strawberry watermelon", "Strawberry ice"]'::jsonb,
--    '["Sour apple ice", "Vanilla ice cream", "Pineapple coconut", "Kiwi dragon berry", "White gummy", "California cherry", "Strawberry watermelon", "Strawberry ice"]'::jsonb),
--   (107,
--    '["13gal", "23gal", "Kitchen", "Lawn"]'::jsonb,
--    '["13 gal", "23 gal", "Kitchen", "Lawn"]'::jsonb),
--   (120,
--    '["20oz", "16oz", "12oz", "8oz"]'::jsonb,
--    '["20 oz", "16 oz", "12 oz", "8 oz"]'::jsonb),
--   (122,
--    '["Case"]'::jsonb,
--    '[]'::jsonb),
--   (123,
--    '["Case"]'::jsonb,
--    '[]'::jsonb),
--   (124,
--    '["Case"]'::jsonb,
--    '[]'::jsonb),
--   (125,
--    '["Big", "Small", "Medium"]'::jsonb,
--    '["Small", "Medium", "Big"]'::jsonb),
--   (150,
--    '["IPhone", "Type C", "Android", "Car charger", "Home charger", "IPhone To type C", "Type C To Type C", "Home charger with type C"]'::jsonb,
--    '["iPhone (Lightning)", "USB-C", "Android", "Car charger", "Home charger", "Lightning to USB-C", "USB-C to USB-C", "Home charger with USB-C"]'::jsonb),
--   (162,
--    '["Regular", "King size", "Almond reg", "Almond king size"]'::jsonb,
--    '["Regular", "King size", "Almond, regular", "Almond, king size"]'::jsonb),
--   (163,
--    '["Yellow reg", "Yellow share size", "Chocolate reg", "Chocolate king size"]'::jsonb,
--    '["Yellow, regular", "Yellow, share size", "Chocolate, regular", "Chocolate, king size"]'::jsonb),
--   (164,
--    '["Regular", "King size", "Vanilla reg", "Vanilla king size"]'::jsonb,
--    '["Regular", "King size", "Vanilla, regular", "Vanilla, king size"]'::jsonb),
--   (166,
--    '["Cups regular", "Cups king size", "White cups reg", "White cups king size", "Pieces reg", "Pieces king size", "Fast break reg", "Fast break king size"]'::jsonb,
--    '["Cups, regular", "Cups, king size", "White cups, regular", "White cups, king size", "Pieces, regular", "Pieces, king size", "Fast break, regular", "Fast break, king size"]'::jsonb),
--   (169,
--    '["Red reg", "Red king size", "Wildberry reg", "Wildberry king size", "Sour reg", "Sour king size", "Blue reg", "Blue king size"]'::jsonb,
--    '["Red, regular", "Red, king size", "Wildberry, regular", "Wildberry, king size", "Sour, regular", "Sour, king size", "Blue, regular", "Blue, king size"]'::jsonb),
--   (171,
--    '["Milk reg", "Milk king size", "Cookies reg", "Cookies king", "Almond reg", "Almond king", "Mr. Goodbar reg", "Mr. Goodbar king"]'::jsonb,
--    '["Milk, regular", "Milk, king size", "Cookies, regular", "Cookies, king size", "Almond, regular", "Almond, king size", "Mr. Goodbar, regular", "Mr. Goodbar, king size"]'::jsonb),
--   (183,
--    '["Watermelon", "Spearmint", "Peppermint", "Polar ice", "Winter fresh"]'::jsonb,
--    '["Watermelon", "Spearmint", "Peppermint", "Polar ice", "Winterfresh"]'::jsonb),
--   (201,
--    '["5-flavors", "Collision", "Wildberry", "Sours", "Fruit rings", "XO rings", "Exotics"]'::jsonb,
--    '["5 Flavors", "Collision", "Wildberry", "Sours", "Fruit rings", "XO rings", "Exotics"]'::jsonb),
--   (212,
--    '["8lbs", "10lbs"]'::jsonb,
--    '["8 lb", "10 lb"]'::jsonb),
--   (242,
--    '["Gold 100", "Gold king", "Menthol 100", "Menthol king", "Red 100", "Red king"]'::jsonb,
--    '["Gold 100", "Gold king size", "Menthol 100", "Menthol king size", "Red 100", "Red king size"]'::jsonb),
--   (243,
--    '["Gold 100", "Gold king", "Menthol 100", "Menthol king", "Orange 100", "Orange king", "Silver 100", "Silver king"]'::jsonb,
--    '["Gold 100", "Gold king size", "Menthol 100", "Menthol king size", "Orange 100", "Orange king size", "Silver 100", "Silver king size"]'::jsonb),
--   (267,
--    '["Mix"]'::jsonb,
--    '[]'::jsonb),
--   (314,
--    '["Big", "Small", "Medium", "1kg"]'::jsonb,
--    '["Small", "Medium", "Big", "1 kg"]'::jsonb),
--   (329,
--    '["Tips"]'::jsonb,
--    '[]'::jsonb),
--   (330,
--    '["Organic"]'::jsonb,
--    '[]'::jsonb),
--   (331,
--    '["AAA2"]'::jsonb,
--    '["AAA 2-pack"]'::jsonb),
--   (354,
--    '["Small"]'::jsonb,
--    '[]'::jsonb),
--   (356,
--    '["1 gal", "2gal", "5 gal"]'::jsonb,
--    '["1 gal", "2 gal", "5 gal"]'::jsonb),
--   (362,
--    '["M size", "L size"]'::jsonb,
--    '["Medium", "Large"]'::jsonb)
-- ) as v(id, old_variants, new_variants)
-- where p.id = v.id and p.variants = v.new_variants;
--
-- update public.products as p set sku = v.old_sku
-- from (values
--   (12, 'AW-LOOSE-LEAFS-2P', 'AW-LOOSE-LEAFS-2PK'),
--   (15, 'AW-ROYAL-BUNTS-MI', 'AW-ROYAL-BLUNTS-MINI'),
--   (16, 'AW-BACKWOODS-SING', 'AW-BACKWOODS-SINGLES'),
--   (28, 'AW-RHINO-PILLS-2P', 'AW-RHINO-PILLS-2PK'),
--   (38, 'AW-WRIGGLY-SLIM-P', 'AW-WRIGLEY-SLIM-PACK'),
--   (40, 'AW-WRIGGLY-50', 'AW-WRIGLEY-50'),
--   (45, 'AW-ARGO-CORN-STAR', 'AW-ARGO-CORN-STARCH'),
--   (65, 'AW-RAZ-VUE-FULL-K', 'AW-RAZ-VUE-FULL-KIT'),
--   (69, 'AW-SHROOM-PUFF-DI', 'AW-SHROOM-PUFF-DISPOSABLE'),
--   (72, 'AW-SHROOM-PUFF-GU', 'AW-SHROOM-PUFF-GUMMIES'),
--   (84, 'AW-GOOD-TIMES-FLA', 'AW-GOOD-TIMES-FLAT'),
--   (93, 'AW-6PK-BEER-CARRI', 'AW-6PK-BEER-CARRIERS'),
--   (95, 'AW-TRASH-CAN-LINE', 'AW-TRASH-CAN-LINERS'),
--   (99, 'AW-PEAK-ANTIFREEZ', 'AW-PEAK-ANTIFREEZE'),
--   (100, 'AW-CHEAP-ANTIFREE', 'AW-CHEAP-ANTIFREEZE'),
--   (103, 'AW-WINDSHIELD-WAS', 'AW-WINDSHIELD-WASHER'),
--   (109, 'AW-AJAX-DISHWASHE', 'AW-AJAX-DISH-LIQUID'),
--   (110, 'AW-BRILLO-DISHWAS', 'AW-BRILLO-DISH-LIQUID'),
--   (116, 'AW-IRISH-SPRING-S', 'AW-IRISH-SPRING-SOAP'),
--   (117, 'AW-AWESOME-LAUNDR', 'AW-AWESOME-LAUNDRY'),
--   (128, 'AW-FABULOUSO', 'AW-FABULOSO'),
--   (129, 'AW-HOME-AIR-FRESH', 'AW-HOME-AIR-FRESHENERS'),
--   (130, 'AW-BRILLO-BASICS-', 'AW-BRILLO-BASICS'),
--   (134, 'AW-RUBBING-ALCOHO', 'AW-RUBBING-ALCOHOL'),
--   (138, 'AW-CHARCOAL-LIGHT', 'AW-CHARCOAL-LIGHTER'),
--   (140, 'AW-TROPICANA-SMAL', 'AW-TROPICANA-SMALL'),
--   (153, 'AW-WHITE-LONG-SLE', 'AW-WHITE-LONG-SLEEVE'),
--   (154, 'AW-BLACK-LONG-SLE', 'AW-BLACK-LONG-SLEEVE'),
--   (175, 'AW-CHICO-STICK-JA', 'AW-CHICK-O-STICK-JAR'),
--   (179, 'AW-LAFFY-TAFFY-JA', 'AW-LAFFY-TAFFY-JAR'),
--   (180, 'AW-LAFFY-TAFFY-RO', 'AW-LAFFY-TAFFY-ROPES'),
--   (207, 'AW-20OZ-MINUTE-MA', 'AW-20OZ-MINUTE-MAID'),
--   (208, 'AW-12OZ-MINUTE-MA', 'AW-12OZ-MINUTE-MAID'),
--   (219, 'AW-HAPPY-VALENTIN', 'AW-HAPPY-VALENTINES'),
--   (222, 'AW-PEPCID-COMPLET', 'AW-PEPCID-COMPLETE'),
--   (225, 'AW-WOMEN-DEODORAN', 'AW-WOMEN-DEODORANT'),
--   (233, 'AW-NESQUICK', 'AW-NESQUIK'),
--   (238, 'AW-GAMBLER-BAGS-B', 'AW-GAMBLER-BAGS-BIG'),
--   (239, 'AW-GAMBLER-BAGS-S', 'AW-GAMBLER-BAGS-SMALL'),
--   (245, 'AW-BLUNTEFFECT-IN', 'AW-BLUNTEFFECT-INCENSE'),
--   (247, 'AW-LATTAFA-AIR-FR', 'AW-LATTAFA-AIR-FRESHENER'),
--   (258, 'AW-PSYCHED-PRE-RO', 'AW-PSYCHED-PRE-ROLLS'),
--   (266, 'AW-BLUE-WOLF-HONE', 'AW-BLUE-WOLF-HONEY'),
--   (271, 'AW-SNICKERS-CHOCO', 'AW-SNICKERS-CHOCOLATE'),
--   (273, 'AW-LOOSE-LEAFS-SP', 'AW-LOOSE-LEAFS-SPLITS'),
--   (274, 'AW-RAW-GUARANA-WR', 'AW-RAW-GUARANA-WRAPS'),
--   (275, 'AW-JOLLY-RANCHER-', 'AW-JOLLY-RANCHER'),
--   (276, 'AW-NOW-AND-LATER-', 'AW-NOW-AND-LATER-GIANT'),
--   (281, 'AW-HUSH-HIT-PRE-R', 'AW-HUSH-HIT-PRE-ROLLS'),
--   (285, 'AW-SHROOM-BANG-PR', 'AW-SHROOM-BANG-PRE-ROLLS'),
--   (286, 'AW-AA-CELLULAR-BL', 'AW-AA-CELLULAR-BLUETOOTH'),
--   (288, 'AW-BLUE-MONKEY-PR', 'AW-BLUE-MONKEY-PRE-ROLLS'),
--   (289, 'AW-PSYCHED-DISPOS', 'AW-PSYCHED-DISPOSABLE'),
--   (292, 'AW-ELECTROLYTE', 'AW-ELECTROLIT'),
--   (296, 'AW-JELLY-HOLES-PR', 'AW-JELLY-HOLES-PRE-ROLLS'),
--   (298, 'AW-SHROOM-ROLLS-P', 'AW-SHROOM-ROLLS-PRE-ROLLS'),
--   (300, 'AW-MELTED-MUSHROO', 'AW-MELTED-MUSHROOM'),
--   (302, 'AW-BETTER-ME-PILL', 'AW-BETTER-ME-PILLS'),
--   (303, 'AW-HIGH-GRAVITY-P', 'AW-HIGH-GRAVITY-PILLS'),
--   (304, 'AW-THIRD-EYE-PILL', 'AW-THIRD-EYE-PILLS'),
--   (306, 'AW-STONED-MUSHROO', 'AW-STONED-MUSHROOM'),
--   (307, 'AW-STONED-HONEY-M', 'AW-STONED-HONEY-MUSHROOM'),
--   (311, 'AW-GEEKBAR-MATE-P', 'AW-GEEKBAR-MATE-PODS'),
--   (312, 'AW-STONED-BLUE-LO', 'AW-STONED-BLUE-LOTUS'),
--   (313, 'AW-PSYCHED-BLUE-L', 'AW-PSYCHED-BLUE-LOTUS'),
--   (314, 'AW-COCO-NARA-CHAR', 'AW-COCO-NARA-CHARCOAL'),
--   (315, 'AW-ALFAKHER-50-GR', 'AW-ALFAKHER-50-GRAM'),
--   (316, 'AW-ALFAKHER-250-G', 'AW-ALFAKHER-250-GRAM'),
--   (323, 'AW-BEER-SALTS-BOT', 'AW-BEER-SALTS-BOTTLES'),
--   (324, 'AW-BEER-SALTS-PAC', 'AW-BEER-SALTS-PACKETS'),
--   (329, 'AW-RAW', 'AW-RAW-TIPS'),
--   (332, 'AW-BLACK-TIGER-HO', 'AW-BLACK-TIGER-HONEY'),
--   (333, 'AW-GAIN-DISHWASHE', 'AW-GAIN-DISH-LIQUID'),
--   (337, 'AW-BOB-MARLEY-PAP', 'AW-BOB-MARLEY-PAPERS'),
--   (339, 'AW-BILLIONAIRE-WR', 'AW-BILLIONAIRE-WRAPS'),
--   (340, 'AW-SLAPWOODS-SING', 'AW-SLAPWOODS-SINGLES'),
--   (341, 'AW-SILLY-DOTS-PIL', 'AW-SILLY-DOTS-PILLS'),
--   (342, 'AW-DUBAI-CHOCOLAT', 'AW-DUBAI-CHOCOLATE'),
--   (347, 'AW-ZIGZAG-HEMP-WR', 'AW-ZIGZAG-HEMP-WRAPS'),
--   (351, 'AW-UNCLE-AL-S-COO', 'AW-UNCLE-AL-S-COOKIES'),
--   (352, 'AW-LOUISIANA-HOT-', 'AW-LOUISIANA-HOT'),
--   (357, 'AW-STARBUST-BARS', 'AW-STARBURST-BARS'),
--   (358, 'AW-LIFESAVER-SHAR', 'AW-LIFESAVER-SHARE'),
--   (361, 'AW-DOMINOES-SUGAR', 'AW-DOMINO-SUGAR'),
--   (362, 'AW-DISPOSABLE-GLO', 'AW-DISPOSABLE-GLOVES'),
--   (367, 'AW-LOOSE-LEAFS-5P', 'AW-LOOSE-LEAFS-5PK')
-- ) as v(id, old_sku, new_sku)
-- where p.id = v.id and p.sku = v.new_sku;
